/**
 * Health Library dataset — the articles published on
 * srmglobalhospitals.com/blogs/, in the order that page lists them
 * (WordPress date-descending, newest first).
 *
 * Titles, links, images, dates and running order were taken from the live
 * site; cover images were downloaded into `public/images/blog/` so the page
 * does not hotlink the old site. Specialty tags and read times come from the
 * design reference; where a post was missing from it, the specialty was
 * assigned from the article subject and the read time computed from the
 * article's word count at 200 wpm.
 *
 * `href` points at the in-app article route. Only
 * `/blog/multiple-sclerosis-expert-care` exists so far — it is mapped by hand
 * below because the live slug differs. The rest resolve once their article
 * pages are built, which is why the cards render as plain `<a>`: `typedRoutes`
 * rejects a `next/link` href that has no matching route yet.
 */

export type Specialty =
  | "Cardiology"
  | "Neurology"
  | "Orthopaedics"
  | "Diabetes"
  | "Gastro"
  | "Women's Health"
  | "Paediatrics"
  | "Pulmonology";

/** Filter pill order and dot colours, both from the design reference. */
export const SPECIALTIES: { name: Specialty; color: string }[] = [
  { name: "Cardiology", color: "#ef4444" },
  { name: "Neurology", color: "#8b3dff" },
  { name: "Orthopaedics", color: "#f59e0b" },
  { name: "Diabetes", color: "#14b8a6" },
  { name: "Gastro", color: "#ec4899" },
  { name: "Women's Health", color: "#f43f5e" },
  { name: "Paediatrics", color: "#3b82f6" },
  { name: "Pulmonology", color: "#06b6d4" },
];

const SPECIALTY_COLORS = new Map(SPECIALTIES.map((s) => [s.name, s.color]));

export function specialtyColor(name: Specialty): string {
  return SPECIALTY_COLORS.get(name) ?? "var(--purple)";
}

export type BlogPost = {
  slug: string;
  title: string;
  href: string;
  /** Cover image under `public/`; `null` for the one post the live site has no featured image for. */
  image: string | null;
  specialty: Specialty;
  readMinutes: number;
  /** ISO date (YYYY-MM-DD), used for the "Most recent" sort. */
  date: string;
};

export const blogPosts: BlogPost[] = [
  {
    slug: "personalised-orthopedic-rehabilitation-for-faster-recovery",
    title: "Personalised Orthopedic Rehabilitation for Faster Recovery",
    href: "/blog/personalised-orthopedic-rehabilitation-for-faster-recovery",
    image: "/images/blog/srm-blog25-img1.webp",
    specialty: "Orthopaedics",
    readMinutes: 4,
    date: "2026-03-30",
  },
  {
    slug: "empower-your-neurological-rehabilitation-journey",
    title: "Empower Your Neurological Rehabilitation Journey",
    href: "/blog/empower-your-neurological-rehabilitation-journey",
    image: "/images/blog/srm-blog24-img1.webp",
    specialty: "Neurology",
    readMinutes: 6,
    date: "2026-08-04",
  },
  {
    slug: "expert-physiotherapy-for-geriatric-rehabilitation",
    title: "Expert Physiotherapy for Geriatric Rehabilitation",
    href: "/blog/expert-physiotherapy-for-geriatric-rehabilitation",
    image: "/images/blog/srm-blog23-img1.webp",
    specialty: "Orthopaedics",
    readMinutes: 6,
    date: "2026-08-04",
  },
  {
    slug: "pulmonary-rehabilitation-for-effective-respiratory-health",
    title: "Pulmonary Rehabilitation for Effective Respiratory Health",
    href: "/blog/pulmonary-rehabilitation-for-effective-respiratory-health",
    image: "/images/blog/srm-blog22-img1.webp",
    specialty: "Pulmonology",
    readMinutes: 6,
    date: "2026-08-04",
  },
  {
    slug: "empowering-independence-advanced-assistive-device-technology",
    title: "Empowering Independence: Advanced Assistive Device Technology",
    href: "/blog/empowering-independence-advanced-assistive-device-technology",
    image: "/images/blog/empowering-independence-advanced-assistive-device-technology.jpeg",
    specialty: "Orthopaedics",
    readMinutes: 5,
    date: "2026-03-31",
  },
  {
    slug: "sciatica-pain-treatment-understand-the-cause-and-find-the-right-relief",
    title: "Sciatica Pain Treatment: Understand the Cause and Find the Right Relief",
    href: "/blog/sciatica-pain-treatment-understand-the-cause-and-find-the-right-relief",
    image: "/images/blog/sciatica-pain-treatment-understand-the-cause-and-find-the-right-relief.jpeg",
    specialty: "Orthopaedics",
    readMinutes: 11,
    date: "2026-04-01",
  },
  {
    slug: "types-of-cerebral-palsy-what-it-means-for-your-child",
    title: "Types of Cerebral Palsy: What It Means for Your Child?",
    href: "/blog/types-of-cerebral-palsy-what-it-means-for-your-child",
    image: "/images/blog/types-of-cerebral-palsy-what-it-means-for-your-child.jpeg",
    specialty: "Neurology",
    readMinutes: 13,
    date: "2026-04-01",
  },
  {
    slug: "multiple-sclerosis-treatment-what-expert-care-at-the-right-time-can-do",
    title: "Multiple Sclerosis Treatment: What Expert Care at the Right Time Can Do?",
    href: "/blog/multiple-sclerosis-expert-care",
    image: "/images/blog/multiple-sclerosis-treatment-what-expert-care-at-the-right-time-can-do.jpeg",
    specialty: "Neurology",
    readMinutes: 15,
    date: "2026-05-14",
  },
  {
    slug: "chest-pain-due-to-gas-when-is-it-harmless-when-you-should-worry",
    title: "Chest Pain Due to Gas: When is It Harmless? When You Should Worry?",
    href: "/blog/chest-pain-due-to-gas-when-is-it-harmless-when-you-should-worry",
    image: "/images/blog/chest-pain-due-to-gas-when-is-it-harmless-when-you-should-worry.jpeg",
    specialty: "Cardiology",
    readMinutes: 9,
    date: "2026-04-01",
  },
  {
    slug: "right-side-chest-pain-what-your-symptoms-could-be-telling-you",
    title: "Right Side Chest Pain: What Your Symptoms Could Be Telling You?",
    href: "/blog/right-side-chest-pain-what-your-symptoms-could-be-telling-you",
    image: "/images/blog/right-side-chest-pain-what-your-symptoms-could-be-telling-you.jpeg",
    specialty: "Cardiology",
    readMinutes: 6,
    date: "2026-04-01",
  },
  {
    slug: "prp-injection-knee-therapy-an-effective-non-surgical-way-to-manage-knee-pain",
    title: "PRP Injection Knee Therapy: An Effective Non-surgical Way to Manage Knee Pain",
    href: "/blog/prp-injection-knee-therapy-an-effective-non-surgical-way-to-manage-knee-pain",
    image: "/images/blog/prp-injection-knee-therapy-an-effective-non-surgical-way-to-manage-knee-pain.jpeg",
    specialty: "Orthopaedics",
    readMinutes: 5,
    date: "2026-04-01",
  },
  {
    slug: "speech-therapy-techniques-for-real-life-communication-challenges",
    title: "Speech Therapy Techniques for Real-life Communication Challenges",
    href: "/blog/speech-therapy-techniques-for-real-life-communication-challenges",
    image: "/images/blog/speech-therapy-techniques-for-real-life-communication-challenges.jpeg",
    specialty: "Neurology",
    readMinutes: 5,
    date: "2026-04-01",
  },
  {
    slug: "speech-language-therapy-for-autism-connect-express-and-understand-the-world-around-you",
    title: "Speech-language Therapy for Autism: Connect, Express, and Understand the World Around You",
    href: "/blog/speech-language-therapy-for-autism-connect-express-and-understand-the-world-around-you",
    image: "/images/blog/speech-language-therapy-for-autism-connect-express-and-understand-the-world-around-you.jpeg",
    specialty: "Paediatrics",
    readMinutes: 5,
    date: "2026-04-01",
  },
  {
    slug: "occupational-therapy-for-children-expert-support-for-real-life-development",
    title: "Occupational Therapy for Children: Expert Support for Real-life Development",
    href: "/blog/occupational-therapy-for-children-expert-support-for-real-life-development",
    image: "/images/blog/occupational-therapy-for-children-expert-support-for-real-life-development.jpeg",
    specialty: "Paediatrics",
    readMinutes: 9,
    date: "2026-04-01",
  },
  {
    slug: "recovery-after-stroke-the-steps-forward-for-functional-independence",
    title: "Recovery After Stroke: The Steps Forward for Functional Independence",
    href: "/blog/recovery-after-stroke-the-steps-forward-for-functional-independence",
    image: "/images/blog/recovery-after-stroke-the-steps-forward-for-functional-independence.jpeg",
    specialty: "Neurology",
    readMinutes: 4,
    date: "2026-04-01",
  },
  {
    slug: "white-discharge-during-pregnancy-whats-normal-and-whats-not",
    title: "White Discharge During Pregnancy: What’s Normal and What’s Not",
    href: "/blog/white-discharge-during-pregnancy-whats-normal-and-whats-not",
    image: "/images/blog/white-discharge-during-pregnancy-whats-normal-and-whats-not.jpeg",
    specialty: "Women's Health",
    readMinutes: 9,
    date: "2026-04-01",
  },
  {
    slug: "cervical-stitch-pregnancy-strengthening-the-mothers-for-a-safer-delivery",
    title: "Cervical Stitch Pregnancy: Strengthening the Mothers for a Safer Delivery",
    href: "/blog/cervical-stitch-pregnancy-strengthening-the-mothers-for-a-safer-delivery",
    image: "/images/blog/cervical-stitch-pregnancy-strengthening-the-mothers-for-a-safer-delivery.jpeg",
    specialty: "Women's Health",
    readMinutes: 9,
    date: "2026-04-01",
  },
  {
    slug: "cervical-length-at-20-weeks-what-every-mom-to-be-should-know",
    title: "Cervical Length at 20 Weeks: What Every Mom-to-Be Should Know",
    href: "/blog/cervical-length-at-20-weeks-what-every-mom-to-be-should-know",
    image: "/images/blog/cervical-length-at-20-weeks-what-every-mom-to-be-should-know.jpeg",
    specialty: "Women's Health",
    readMinutes: 8,
    date: "2026-03-31",
  },
  {
    slug: "cervical-lymph-nodes-the-bodys-defence-you-didnt-know-about",
    title: "Cervical Lymph Nodes: The Body’s Defence You Didn’t Know About",
    href: "/blog/cervical-lymph-nodes-the-bodys-defence-you-didnt-know-about",
    image: "/images/blog/cervical-lymph-nodes-the-bodys-defence-you-didnt-know-about.jpeg",
    specialty: "Neurology",
    readMinutes: 4,
    date: "2026-03-31",
  },
  {
    slug: "cervical-mucus-your-bodys-fertility-guide-explained",
    title: "Cervical Mucus: Your Body’s Fertility Guide Explained",
    href: "/blog/cervical-mucus-your-bodys-fertility-guide-explained",
    image: "/images/blog/cervical-mucus-your-bodys-fertility-guide-explained.jpeg",
    specialty: "Women's Health",
    readMinutes: 8,
    date: "2026-03-31",
  },
  {
    slug: "restoring-hope-through-professional-gait-training",
    title: "Restoring Hope Through Professional Gait Training",
    href: "/blog/restoring-hope-through-professional-gait-training",
    image: "/images/blog/restoring-hope-through-professional-gait-training.jpeg",
    specialty: "Neurology",
    readMinutes: 7,
    date: "2026-03-31",
  },
  {
    slug: "expert-diabetic-foot-care-to-keep-you-moving",
    title: "Expert Diabetic Foot Care to Keep You Moving",
    href: "/blog/expert-diabetic-foot-care-to-keep-you-moving",
    image: "/images/blog/expert-diabetic-foot-care-to-keep-you-moving.jpeg",
    specialty: "Diabetes",
    readMinutes: 4,
    date: "2026-03-31",
  },
  {
    slug: "redefining-life-through-amputation-rehabilitation",
    title: "Redefining Life Through Amputation Rehabilitation",
    href: "/blog/redefining-life-through-amputation-rehabilitation",
    image: "/images/blog/redefining-life-through-amputation-rehabilitation.jpeg",
    specialty: "Orthopaedics",
    readMinutes: 4,
    date: "2026-03-31",
  },
  {
    slug: "get-back-with-the-stronger-heart-effective-cardiac-rehabilitation",
    title: "Get Back With the Stronger Heart: Effective Cardiac Rehabilitation",
    href: "/blog/get-back-with-the-stronger-heart-effective-cardiac-rehabilitation",
    image: "/images/blog/get-back-with-the-stronger-heart-effective-cardiac-rehabilitation.jpeg",
    specialty: "Cardiology",
    readMinutes: 4,
    date: "2026-03-31",
  },
  {
    slug: "empowering-independence-advanced-assistive-device-technology",
    title: "Empowering Independence: Advanced Assistive Device Technology",
    href: "/blog/empowering-independence-advanced-assistive-device-technology",
    image: "/images/blog/empowering-independence-advanced-assistive-device-technology.jpeg",
    specialty: "Orthopaedics",
    readMinutes: 5,
    date: "2026-03-31",
  },
  {
    slug: "pulmonary-rehabilitation-for-effective-respiratory-health",
    title: "Pulmonary Rehabilitation for Effective Respiratory Health",
    href: "/blog/pulmonary-rehabilitation-for-effective-respiratory-health",
    image: "/images/blog/pulmonary-rehabilitation-for-effective-respiratory-health.jpeg",
    specialty: "Pulmonology",
    readMinutes: 5,
    date: "2026-03-31",
  },
  {
    slug: "expert-physiotherapy-for-geriatric-rehabilitation",
    title: "Expert Physiotherapy for Geriatric Rehabilitation",
    href: "/blog/expert-physiotherapy-for-geriatric-rehabilitation",
    image: "/images/blog/expert-physiotherapy-for-geriatric-rehabilitation.jpeg",
    specialty: "Orthopaedics",
    readMinutes: 8,
    date: "2026-03-31",
  },
  {
    slug: "empower-your-neurological-rehabilitation-journey",
    title: "Empower Your Neurological Rehabilitation Journey",
    href: "/blog/empower-your-neurological-rehabilitation-journey",
    image: "/images/blog/empower-your-neurological-rehabilitation-journey.jpeg",
    specialty: "Neurology",
    readMinutes: 8,
    date: "2026-03-31",
  },
  {
    slug: "personalised-orthopedic-rehabilitation-for-faster-recovery",
    title: "Personalised Orthopedic Rehabilitation for Faster Recovery",
    href: "/blog/personalised-orthopedic-rehabilitation-for-faster-recovery",
    image: "/images/blog/personalised-orthopedic-rehabilitation-for-faster-recovery.jpeg",
    specialty: "Orthopaedics",
    readMinutes: 4,
    date: "2026-03-30",
  },
  {
    slug: "power-your-comeback-through-sports-rehabilitation",
    title: "Power Your Comeback Through Sports Rehabilitation",
    href: "/blog/power-your-comeback-through-sports-rehabilitation",
    image: "/images/blog/power-your-comeback-through-sports-rehabilitation.jpeg",
    specialty: "Orthopaedics",
    readMinutes: 8,
    date: "2026-03-30",
  },
  {
    slug: "pediatric-rehabilitation-focused-on-your-children",
    title: "Pediatric Rehabilitation Focused on Your Children",
    href: "/blog/pediatric-rehabilitation-focused-on-your-children",
    image: "/images/blog/pediatric-rehabilitation-focused-on-your-children.jpeg",
    specialty: "Paediatrics",
    readMinutes: 5,
    date: "2026-03-30",
  },
  {
    slug: "why-sarcoidosis-treatment-is-no-longer-a-guessing-game",
    title: "Why Sarcoidosis Treatment is No Longer a Guessing Game?",
    href: "/blog/why-sarcoidosis-treatment-is-no-longer-a-guessing-game",
    image: "/images/blog/why-sarcoidosis-treatment-is-no-longer-a-guessing-game.png",
    specialty: "Pulmonology",
    readMinutes: 9,
    date: "2026-01-14",
  },
  {
    slug: "unlocking-your-movement-a-factual-guide-to-overcoming-frozen-shoulder",
    title: "Unlocking Your Movement: A Factual Guide to Overcoming Frozen Shoulder",
    href: "/blog/unlocking-your-movement-a-factual-guide-to-overcoming-frozen-shoulder",
    image: "/images/blog/unlocking-your-movement-a-factual-guide-to-overcoming-frozen-shoulder.jpeg",
    specialty: "Orthopaedics",
    readMinutes: 9,
    date: "2026-01-14",
  },
  {
    slug: "the-silent-shock-absorber-why-a-meniscus-tear-is-more-than-just-knee-pain",
    title: "The Silent Shock Absorber: Why a Meniscus Tear is More Than Just Knee Pain",
    href: "/blog/the-silent-shock-absorber-why-a-meniscus-tear-is-more-than-just-knee-pain",
    image: "/images/blog/the-silent-shock-absorber-why-a-meniscus-tear-is-more-than-just-knee-pain.jpeg",
    specialty: "Orthopaedics",
    readMinutes: 9,
    date: "2026-01-14",
  },
  {
    slug: "sitting-without-struggle-reclaiming-your-life-from-tailbone-pain",
    title: "Sitting Without Struggle: Reclaiming Your Life from Tailbone Pain",
    href: "/blog/sitting-without-struggle-reclaiming-your-life-from-tailbone-pain",
    image: "/images/blog/sitting-without-struggle-reclaiming-your-life-from-tailbone-pain.jpeg",
    specialty: "Orthopaedics",
    readMinutes: 8,
    date: "2026-01-14",
  },
  {
    slug: "why-do-my-knees-hurt-everything-you-need-to-know-about-knee-osteoarthritis",
    title: "Why Do My Knees Hurt? Everything You Need to Know About Knee Osteoarthritis",
    href: "/blog/why-do-my-knees-hurt-everything-you-need-to-know-about-knee-osteoarthritis",
    image: "/images/blog/why-do-my-knees-hurt-everything-you-need-to-know-about-knee-osteoarthritis.jpeg",
    specialty: "Orthopaedics",
    readMinutes: 7,
    date: "2026-01-14",
  },
  {
    slug: "why-expertise-matters-in-managing-histoplasmosis",
    title: "Why Expertise Matters in Managing Histoplasmosis?",
    href: "/blog/why-expertise-matters-in-managing-histoplasmosis",
    image: "/images/blog/why-expertise-matters-in-managing-histoplasmosis.jpeg",
    specialty: "Pulmonology",
    readMinutes: 5,
    date: "2026-01-14",
  },
  {
    slug: "tuberculosis-treatment-how-it-turns-out-to-be-life-saving-reality",
    title: "Tuberculosis Treatment: How it Turns Out to Be Life-Saving Reality",
    href: "/blog/tuberculosis-treatment-how-it-turns-out-to-be-life-saving-reality",
    image: "/images/blog/tuberculosis-treatment-how-it-turns-out-to-be-life-saving-reality.jpeg",
    specialty: "Pulmonology",
    readMinutes: 7,
    date: "2026-01-14",
  },
  {
    slug: "breathe-new-life-pulmonary-fibrosis-treatments-symptoms-causes-and-complications",
    title: "Breathe New Life: Pulmonary Fibrosis Treatments, Symptoms, Causes and Complications",
    href: "/blog/breathe-new-life-pulmonary-fibrosis-treatments-symptoms-causes-and-complications",
    image: "/images/blog/breathe-new-life-pulmonary-fibrosis-treatments-symptoms-causes-and-complications.jpeg",
    specialty: "Pulmonology",
    readMinutes: 8,
    date: "2026-01-14",
  },
  {
    slug: "the-silent-expansion-breaking-the-cycle-of-bronchiectasis",
    title: "The Silent Expansion: Breaking the Cycle of Bronchiectasis",
    href: "/blog/the-silent-expansion-breaking-the-cycle-of-bronchiectasis",
    image: "/images/blog/the-silent-expansion-breaking-the-cycle-of-bronchiectasis.jpeg",
    specialty: "Pulmonology",
    readMinutes: 6,
    date: "2026-01-14",
  },
  {
    slug: "esophageal-varices-what-happens-when-blood-flow-is-blocked",
    title: "Esophageal Varices: What Happens When Blood Flow Is Blocked",
    href: "/blog/esophageal-varices-what-happens-when-blood-flow-is-blocked",
    image: "/images/blog/esophageal-varices-what-happens-when-blood-flow-is-blocked.jpeg",
    specialty: "Gastro",
    readMinutes: 4,
    date: "2026-01-14",
  },
  {
    slug: "hiatel-hernia-a-threat-to-the-muscle-that-separates",
    title: "Hiatel Hernia- A Threat to the Muscle that Separates",
    href: "/blog/hiatel-hernia-a-threat-to-the-muscle-that-separates",
    image: "/images/blog/hiatel-hernia-a-threat-to-the-muscle-that-separates.jpeg",
    specialty: "Gastro",
    readMinutes: 5,
    date: "2026-01-14",
  },
  {
    slug: "all-about-esophagitis-types-causes-complications-treatments-and-management",
    title: "All About Esophagitis: Types, Causes, Complications, Treatments and Management",
    href: "/blog/all-about-esophagitis-types-causes-complications-treatments-and-management",
    image: "/images/blog/all-about-esophagitis-types-causes-complications-treatments-and-management.jpeg",
    specialty: "Gastro",
    readMinutes: 9,
    date: "2026-01-13",
  },
  {
    slug: "what-is-antral-gastritis-and-why-gut-experts-treat-it-differently",
    title: "What is Antral Gastritis and Why Gut Experts Treat it Differently",
    href: "/blog/what-is-antral-gastritis-and-why-gut-experts-treat-it-differently",
    image: "/images/blog/what-is-antral-gastritis-and-why-gut-experts-treat-it-differently.jpeg",
    specialty: "Gastro",
    readMinutes: 7,
    date: "2026-01-13",
  },
  {
    slug: "what-you-must-know-about-gastritis-causes-symptoms-complications-treatment-and-management",
    title: "What You Must Know About Gastritis- Causes, Symptoms, Complications, Treatment and Management",
    href: "/blog/what-you-must-know-about-gastritis-causes-symptoms-complications-treatment-and-management",
    image: "/images/blog/what-you-must-know-about-gastritis-causes-symptoms-complications-treatment-and-management.jpeg",
    specialty: "Gastro",
    readMinutes: 6,
    date: "2026-01-13",
  },
  {
    slug: "transform-your-health-overcoming-non-alcoholic-fatty-liver-disease",
    title: "Transform Your Health: Overcoming Non-Alcoholic Fatty Liver Disease",
    href: "/blog/transform-your-health-overcoming-non-alcoholic-fatty-liver-disease",
    image: "/images/blog/transform-your-health-overcoming-non-alcoholic-fatty-liver-disease.jpeg",
    specialty: "Gastro",
    readMinutes: 6,
    date: "2025-12-04",
  },
  {
    slug: "gallstone-pancreatitis-what-to-do-now-how-to-heal-faster-and-how-to-prevent-future-attacks",
    title: "Gallstone Pancreatitis- What to Do Now, How to Heal Faster, and How to Prevent Future Attacks",
    href: "/blog/gallstone-pancreatitis-what-to-do-now-how-to-heal-faster-and-how-to-prevent-future-attacks",
    image: "/images/blog/gallstone-pancreatitis-what-to-do-now-how-to-heal-faster-and-how-to-prevent-future-attacks.jpeg",
    specialty: "Gastro",
    readMinutes: 5,
    date: "2025-12-04",
  },
  {
    slug: "what-happens-in-barretts-esophagus-understanding-the-health-changes",
    title: "What Happens in Barrett’s Esophagus? Understanding the Health Changes",
    href: "/blog/what-happens-in-barretts-esophagus-understanding-the-health-changes",
    image: "/images/blog/what-happens-in-barretts-esophagus-understanding-the-health-changes.jpeg",
    specialty: "Gastro",
    readMinutes: 5,
    date: "2025-12-04",
  },
  {
    slug: "helicobacter-pylori-infection-symptoms-diagnosis-and-treatment",
    title: "Helicobacter pylori Infection- Symptoms, Diagnosis, and Treatment",
    href: "/blog/helicobacter-pylori-infection-symptoms-diagnosis-and-treatment",
    image: "/images/blog/helicobacter-pylori-infection-symptoms-diagnosis-and-treatment.jpeg",
    specialty: "Gastro",
    readMinutes: 6,
    date: "2025-12-04",
  },
  {
    slug: "knee-cartilage-damage-explained-early-signs-you-shouldnt-ignore",
    title: "Knee Cartilage Damage Explained: Early Signs You Shouldn’t Ignore",
    href: "/blog/knee-cartilage-damage-explained-early-signs-you-shouldnt-ignore",
    image: "/images/blog/knee-cartilage-damage-explained-early-signs-you-shouldnt-ignore.jpeg",
    specialty: "Orthopaedics",
    readMinutes: 4,
    date: "2025-12-03",
  },
  {
    slug: "labral-tear-shoulder-explained-early-signs-and-how-to-heal-faster",
    title: "Labral Tear Shoulder Explained: Early Signs and How to Heal Faster",
    href: "/blog/labral-tear-shoulder-explained-early-signs-and-how-to-heal-faster",
    image: "/images/blog/labral-tear-shoulder-explained-early-signs-and-how-to-heal-faster.jpeg",
    specialty: "Orthopaedics",
    readMinutes: 4,
    date: "2025-12-03",
  },
  {
    slug: "what-is-hip-impingement-signs-diagnosis-recovery-tips",
    title: "What Is Hip Impingement? Signs, Diagnosis & Recovery Tips",
    href: "/blog/what-is-hip-impingement-signs-diagnosis-recovery-tips",
    image: "/images/blog/what-is-hip-impingement-signs-diagnosis-recovery-tips.jpeg",
    specialty: "Orthopaedics",
    readMinutes: 7,
    date: "2025-12-03",
  },
  {
    slug: "lateral-meniscus-tear-symptoms-causes-and-best-treatment-options",
    title: "Lateral Meniscus Tear: Symptoms, Causes, and Best Treatment Options",
    href: "/blog/lateral-meniscus-tear-symptoms-causes-and-best-treatment-options",
    image: "/images/blog/lateral-meniscus-tear-symptoms-causes-and-best-treatment-options.jpeg",
    specialty: "Orthopaedics",
    readMinutes: 4,
    date: "2025-12-03",
  },
  {
    slug: "top-meniscus-tear-exercises-to-strengthen-your-knee-and-alleviate-pain",
    title: "Top Meniscus Tear Exercises to Strengthen Your Knee and Alleviate Pain",
    href: "/blog/top-meniscus-tear-exercises-to-strengthen-your-knee-and-alleviate-pain",
    image: "/images/blog/top-meniscus-tear-exercises-to-strengthen-your-knee-and-alleviate-pain.jpeg",
    specialty: "Orthopaedics",
    readMinutes: 6,
    date: "2025-12-03",
  },
  {
    slug: "what-is-a-meniscus-tear-signs-treatment-recovery-guide",
    title: "What Is a Meniscus Tear? Signs, Treatment & Recovery Guide",
    href: "/blog/what-is-a-meniscus-tear-signs-treatment-recovery-guide",
    image: "/images/blog/what-is-a-meniscus-tear-signs-treatment-recovery-guide.jpeg",
    specialty: "Orthopaedics",
    readMinutes: 6,
    date: "2025-12-03",
  },
  {
    slug: "microvascular-disease-guide-symptoms-care-long-term-risks",
    title: "Microvascular Disease Guide: Symptoms, Care & Long-Term Risks",
    href: "/blog/microvascular-disease-guide-symptoms-care-long-term-risks",
    image: "/images/blog/microvascular-disease-guide-symptoms-care-long-term-risks.jpeg",
    specialty: "Cardiology",
    readMinutes: 8,
    date: "2025-12-03",
  },
  {
    slug: "takotsubo-cardiomyopathy-how-stress-affects-the-heart",
    title: "Takotsubo Cardiomyopathy: How Stress Affects the Heart",
    href: "/blog/takotsubo-cardiomyopathy-how-stress-affects-the-heart",
    image: "/images/blog/takotsubo-cardiomyopathy-how-stress-affects-the-heart.jpeg",
    specialty: "Cardiology",
    readMinutes: 6,
    date: "2025-12-02",
  },
  {
    slug: "hfpef-diastolic-heart-failure-causes-effects-and-treatment",
    title: "HFpEF (Diastolic Heart Failure): Causes, Effects, and Treatment",
    href: "/blog/hfpef-diastolic-heart-failure-causes-effects-and-treatment",
    image: "/images/blog/hfpef-diastolic-heart-failure-causes-effects-and-treatment.png",
    specialty: "Cardiology",
    readMinutes: 4,
    date: "2025-12-02",
  },
  {
    slug: "atrial-fibrillation-symptoms-causes-risks-and-treatment",
    title: "Atrial Fibrillation Symptoms, Causes, Risks, and Treatment",
    href: "/blog/atrial-fibrillation-symptoms-causes-risks-and-treatment",
    image: "/images/blog/atrial-fibrillation-symptoms-causes-risks-and-treatment.jpeg",
    specialty: "Cardiology",
    readMinutes: 9,
    date: "2025-12-02",
  },
  {
    slug: "what-are-rheumatoid-arthritis-deformities-causes-and-solutions",
    title: "What are Rheumatoid Arthritis Deformities? Causes and Solutions",
    href: "/blog/what-are-rheumatoid-arthritis-deformities-causes-and-solutions",
    image: "/images/blog/what-are-rheumatoid-arthritis-deformities-causes-and-solutions.jpeg",
    specialty: "Orthopaedics",
    readMinutes: 7,
    date: "2025-11-04",
  },
  {
    slug: "find-the-best-doctor-for-rheumatoid-arthritis-in-chennai-today",
    title: "Find the Best Doctor for Rheumatoid Arthritis in Chennai Today",
    href: "/blog/find-the-best-doctor-for-rheumatoid-arthritis-in-chennai-today",
    image: "/images/blog/find-the-best-doctor-for-rheumatoid-arthritis-in-chennai-today.jpeg",
    specialty: "Orthopaedics",
    readMinutes: 8,
    date: "2025-11-04",
  },
  {
    slug: "effective-acl-tear-treatment-options-for-recovery-and-rehabilitation",
    title: "Effective ACL Tear Treatment: Options for Recovery and Rehabilitation",
    href: "/blog/effective-acl-tear-treatment-options-for-recovery-and-rehabilitation",
    image: "/images/blog/effective-acl-tear-treatment-options-for-recovery-and-rehabilitation.jpeg",
    specialty: "Orthopaedics",
    readMinutes: 4,
    date: "2025-11-04",
  },
  {
    slug: "what-is-acl-tear-surgery-essential-insights-and-recovery-tips",
    title: "What is ACL Tear Surgery? Essential Insights and Recovery Tips",
    href: "/blog/what-is-acl-tear-surgery-essential-insights-and-recovery-tips",
    image: "/images/blog/what-is-acl-tear-surgery-essential-insights-and-recovery-tips.jpeg",
    specialty: "Orthopaedics",
    readMinutes: 7,
    date: "2025-11-04",
  },
  {
    slug: "what-is-partial-acl-tear-recovery-time-without-surgery",
    title: "What is Partial ACL Tear Recovery Time Without Surgery",
    href: "/blog/what-is-partial-acl-tear-recovery-time-without-surgery",
    image: "/images/blog/what-is-partial-acl-tear-recovery-time-without-surgery.jpeg",
    specialty: "Orthopaedics",
    readMinutes: 4,
    date: "2025-11-04",
  },
  {
    slug: "the-best-complete-acl-tear-treatment-options-for-effective-recovery",
    title: "The Best Complete ACL Tear Treatment Options for Effective Recovery",
    href: "/blog/the-best-complete-acl-tear-treatment-options-for-effective-recovery",
    image: "/images/blog/the-best-complete-acl-tear-treatment-options-for-effective-recovery.jpeg",
    specialty: "Orthopaedics",
    readMinutes: 8,
    date: "2025-11-04",
  },
  {
    slug: "what-is-hip-impingement-causes-symptoms-and-treatment-options",
    title: "What is Hip Impingement: Causes, Symptoms, and Treatment Options",
    href: "/blog/what-is-hip-impingement-causes-symptoms-and-treatment-options",
    image: "/images/blog/what-is-hip-impingement-causes-symptoms-and-treatment-options.jpeg",
    specialty: "Orthopaedics",
    readMinutes: 6,
    date: "2025-11-04",
  },
  {
    slug: "what-is-interstitial-cystitis-symptoms-causes-and-treatments",
    title: "What is Interstitial Cystitis: Symptoms, Causes, and Treatments?",
    href: "/blog/what-is-interstitial-cystitis-symptoms-causes-and-treatments",
    image: "/images/blog/what-is-interstitial-cystitis-symptoms-causes-and-treatments.jpeg",
    specialty: "Women's Health",
    readMinutes: 9,
    date: "2025-11-04",
  },
  {
    slug: "what-is-knee-cartilage-damage-causes-symptoms-and-treatments",
    title: "What is Knee Cartilage Damage? Causes, Symptoms, and Treatments",
    href: "/blog/what-is-knee-cartilage-damage-causes-symptoms-and-treatments",
    image: "/images/blog/what-is-knee-cartilage-damage-causes-symptoms-and-treatments.jpeg",
    specialty: "Orthopaedics",
    readMinutes: 8,
    date: "2025-11-04",
  },
  {
    slug: "managing-overactive-bladder-effective-solutions-and-relief-options",
    title: "Managing Overactive Bladder: Effective Solutions and Relief Options",
    href: "/blog/managing-overactive-bladder-effective-solutions-and-relief-options",
    image: "/images/blog/managing-overactive-bladder-effective-solutions-and-relief-options.jpeg",
    specialty: "Women's Health",
    readMinutes: 6,
    date: "2025-11-04",
  },
  {
    slug: "comprehensive-guide-to-labral-tear-shoulder-symptoms-and-treatments",
    title: "Comprehensive Guide to Labral Tear Shoulder: Symptoms and Treatments",
    href: "/blog/comprehensive-guide-to-labral-tear-shoulder-symptoms-and-treatments",
    image: "/images/blog/comprehensive-guide-to-labral-tear-shoulder-symptoms-and-treatments.jpeg",
    specialty: "Orthopaedics",
    readMinutes: 8,
    date: "2025-11-04",
  },
  {
    slug: "what-is-a-rotator-cuff-tear-symptoms-diagnosis-and-treatment",
    title: "What is a Rotator Cuff Tear? Symptoms, Diagnosis, and Treatment",
    href: "/blog/what-is-a-rotator-cuff-tear-symptoms-diagnosis-and-treatment",
    image: "/images/blog/what-is-a-rotator-cuff-tear-symptoms-diagnosis-and-treatment.jpeg",
    specialty: "Orthopaedics",
    readMinutes: 5,
    date: "2025-11-04",
  },
  {
    slug: "effective-meniscus-tear-treatment-options-for-relief-and-recovery",
    title: "Effective Meniscus Tear Treatment: Options for Relief and Recovery",
    href: "/blog/effective-meniscus-tear-treatment-options-for-relief-and-recovery",
    image: "/images/blog/effective-meniscus-tear-treatment-options-for-relief-and-recovery.jpeg",
    specialty: "Orthopaedics",
    readMinutes: 9,
    date: "2025-11-04",
  },
  {
    slug: "what-is-a-urinary-tract-infection-causes-symptoms-and-treatment",
    title: "What is a Urinary Tract Infection? Causes, Symptoms, and Treatment",
    href: "/blog/what-is-a-urinary-tract-infection-causes-symptoms-and-treatment",
    image: "/images/blog/what-is-a-urinary-tract-infection-causes-symptoms-and-treatment.jpeg",
    specialty: "Women's Health",
    readMinutes: 4,
    date: "2025-11-04",
  },
  {
    slug: "urinary-incontinence-after-childbirth-causes-and-remedies",
    title: "Urinary Incontinence After Childbirth: Causes and Remedies",
    href: "/blog/urinary-incontinence-after-childbirth-causes-and-remedies",
    image: "/images/blog/urinary-incontinence-after-childbirth-causes-and-remedies.jpeg",
    specialty: "Women's Health",
    readMinutes: 4,
    date: "2025-11-04",
  },
  {
    slug: "what-is-vaginal-vault-prolapse-symptoms-causes-and-solutions",
    title: "What Is Vaginal Vault Prolapse: Symptoms, Causes, and Solutions",
    href: "/blog/what-is-vaginal-vault-prolapse-symptoms-causes-and-solutions",
    image: "/images/blog/what-is-vaginal-vault-prolapse-symptoms-causes-and-solutions.jpeg",
    specialty: "Women's Health",
    readMinutes: 9,
    date: "2025-11-04",
  },
  {
    slug: "understanding-seronegative-arthritis-symptoms-causes-and-treatments",
    title: "Understanding Seronegative Arthritis: Symptoms, Causes, and Treatments",
    href: "/blog/understanding-seronegative-arthritis-symptoms-causes-and-treatments",
    image: "/images/blog/understanding-seronegative-arthritis-symptoms-causes-and-treatments.jpeg",
    specialty: "Orthopaedics",
    readMinutes: 5,
    date: "2025-11-04",
  },
  {
    slug: "understanding-acl-tear-symptoms-treatment-and-recovery-options",
    title: "Understanding ACL Tear: Symptoms, Treatment, and Recovery Options",
    href: "/blog/understanding-acl-tear-symptoms-treatment-and-recovery-options",
    image: "/images/blog/understanding-acl-tear-symptoms-treatment-and-recovery-options.png",
    specialty: "Orthopaedics",
    readMinutes: 6,
    date: "2025-08-13",
  },
  {
    slug: "effective-tennis-elbow-treatment-relieve-pain-and-restore-mobility",
    title: "Effective Tennis Elbow Treatment: Relieve Pain and Restore Mobility",
    href: "/blog/effective-tennis-elbow-treatment-relieve-pain-and-restore-mobility",
    image: "/images/blog/effective-tennis-elbow-treatment-relieve-pain-and-restore-mobility.png",
    specialty: "Orthopaedics",
    readMinutes: 4,
    date: "2025-08-13",
  },
  {
    slug: "understanding-feeding-on-demand-a-guide-to-your-babys-needs",
    title: "Understanding Feeding on Demand: A Guide to Your Baby’s Needs",
    href: "/blog/understanding-feeding-on-demand-a-guide-to-your-babys-needs",
    image: "/images/blog/understanding-feeding-on-demand-a-guide-to-your-babys-needs.png",
    specialty: "Paediatrics",
    readMinutes: 5,
    date: "2025-08-13",
  },
  {
    slug: "the-best-baby-feeding-position-comfort-for-you-and-your-little-one",
    title: "The Best Baby Feeding Position: Comfort for You and Your Little One",
    href: "/blog/the-best-baby-feeding-position-comfort-for-you-and-your-little-one",
    image: "/images/blog/the-best-baby-feeding-position-comfort-for-you-and-your-little-one.png",
    specialty: "Paediatrics",
    readMinutes: 4,
    date: "2025-08-13",
  },
  {
    slug: "mastering-the-rotablator-essential-insights-for-effective-atherectomy",
    title: "Mastering the Rotablator: Essential Insights for Effective Atherectomy",
    href: "/blog/mastering-the-rotablator-essential-insights-for-effective-atherectomy",
    image: "/images/blog/mastering-the-rotablator-essential-insights-for-effective-atherectomy.png",
    specialty: "Cardiology",
    readMinutes: 7,
    date: "2025-08-13",
  },
  {
    slug: "understanding-total-knee-replacement-what-to-expect-and-recovery-tips",
    title: "Understanding Total Knee Replacement: What to Expect and Recovery Tips",
    href: "/blog/understanding-total-knee-replacement-what-to-expect-and-recovery-tips",
    image: "/images/blog/understanding-total-knee-replacement-what-to-expect-and-recovery-tips.png",
    specialty: "Orthopaedics",
    readMinutes: 6,
    date: "2025-08-13",
  },
  {
    slug: "effective-arrhythmia-treatment-options-benefits-and-what-to-expect",
    title: "Effective Arrhythmia Treatment: Options, Benefits, and What to Expect",
    href: "/blog/effective-arrhythmia-treatment-options-benefits-and-what-to-expect",
    image: "/images/blog/effective-arrhythmia-treatment-options-benefits-and-what-to-expect.png",
    specialty: "Cardiology",
    readMinutes: 7,
    date: "2025-08-13",
  },
  {
    slug: "essential-guide-to-heart-failure-treatment-options-and-considerations",
    title: "Essential Guide to Heart Failure Treatment Options and Considerations",
    href: "/blog/essential-guide-to-heart-failure-treatment-options-and-considerations",
    image: "/images/blog/essential-guide-to-heart-failure-treatment-options-and-considerations.png",
    specialty: "Cardiology",
    readMinutes: 9,
    date: "2025-08-13",
  },
  {
    slug: "heart-stent-operation-a-comprehensive-overview-of-the-procedure",
    title: "Heart Stent Operation: A Comprehensive Overview of the Procedure",
    href: "/blog/heart-stent-operation-a-comprehensive-overview-of-the-procedure",
    image: "/images/blog/heart-stent-operation-a-comprehensive-overview-of-the-procedure.png",
    specialty: "Cardiology",
    readMinutes: 6,
    date: "2025-07-30",
  },
  {
    slug: "understanding-tevar-a-guide-to-thoracic-endovascular-aneurysm-repair",
    title: "Understanding TEVAR: A Guide to Thoracic Endovascular Aneurysm Repair",
    href: "/blog/understanding-tevar-a-guide-to-thoracic-endovascular-aneurysm-repair",
    image: "/images/blog/understanding-tevar-a-guide-to-thoracic-endovascular-aneurysm-repair.png",
    specialty: "Cardiology",
    readMinutes: 5,
    date: "2025-07-30",
  },
  {
    slug: "understanding-carotid-endarterectomy-benefits-and-recovery-insights",
    title: "Understanding Carotid Endarterectomy: Benefits and Recovery Insights",
    href: "/blog/understanding-carotid-endarterectomy-benefits-and-recovery-insights",
    image: "/images/blog/understanding-carotid-endarterectomy-benefits-and-recovery-insights.png",
    specialty: "Cardiology",
    readMinutes: 6,
    date: "2025-07-30",
  },
  {
    slug: "essential-guide-to-the-anomaly-scan-what-to-expect-and-understand",
    title: "Essential Guide to the Anomaly Scan: What to Expect and Understand",
    href: "/blog/essential-guide-to-the-anomaly-scan-what-to-expect-and-understand",
    image: "/images/blog/essential-guide-to-the-anomaly-scan-what-to-expect-and-understand.png",
    specialty: "Women's Health",
    readMinutes: 6,
    date: "2025-07-25",
  },
  {
    slug: "intermittent-fasting-and-heart-disease-risks-and-considerations-explained",
    title: "Intermittent Fasting and Heart Disease: Risks and Considerations Explained",
    href: "/blog/intermittent-fasting-and-heart-disease-risks-and-considerations-explained",
    image: "/images/blog/intermittent-fasting-and-heart-disease-risks-and-considerations-explained.png",
    specialty: "Cardiology",
    readMinutes: 5,
    date: "2025-07-24",
  },
  {
    slug: "effective-l5-s1-disc-bulge-treatment-symptoms-causes-and-solutions",
    title: "Effective L5 S1 Disc Bulge Treatment: Symptoms, Causes, and Solutions",
    href: "/blog/effective-l5-s1-disc-bulge-treatment-symptoms-causes-and-solutions",
    image: "/images/blog/effective-l5-s1-disc-bulge-treatment-symptoms-causes-and-solutions.png",
    specialty: "Orthopaedics",
    readMinutes: 9,
    date: "2025-07-24",
  },
  {
    slug: "relief-strategies-for-l4-l5-disc-bulge-effective-care-options",
    title: "Relief Strategies for L4 L5 Disc Bulge: Effective Care Options",
    href: "/blog/relief-strategies-for-l4-l5-disc-bulge-effective-care-options",
    image: "/images/blog/relief-strategies-for-l4-l5-disc-bulge-effective-care-options.png",
    specialty: "Orthopaedics",
    readMinutes: 6,
    date: "2025-07-23",
  },
  {
    slug: "effective-tail-bone-pain-treatment-options-for-relief-and-recovery",
    title: "Effective Tail Bone Pain Treatment: Options for Relief and Recovery",
    href: "/blog/effective-tail-bone-pain-treatment-options-for-relief-and-recovery",
    image: "/images/blog/effective-tail-bone-pain-treatment-options-for-relief-and-recovery.png",
    specialty: "Orthopaedics",
    readMinutes: 9,
    date: "2025-07-23",
  },
  {
    slug: "understanding-esophageal-ulcer-symptoms-causes-and-treatments",
    title: "Understanding Esophageal Ulcer: Symptoms, Causes, and Treatments",
    href: "/blog/understanding-esophageal-ulcer-symptoms-causes-and-treatments",
    image: "/images/blog/understanding-esophageal-ulcer-symptoms-causes-and-treatments.png",
    specialty: "Gastro",
    readMinutes: 9,
    date: "2025-07-22",
  },
  {
    slug: "antral-gastritis-causes-best-treatments-and-symptoms-explained",
    title: "Antral Gastritis: Causes, Best Treatments, and Symptoms Explained",
    href: "/blog/antral-gastritis-causes-best-treatments-and-symptoms-explained",
    image: "/images/blog/antral-gastritis-causes-best-treatments-and-symptoms-explained.png",
    specialty: "Gastro",
    readMinutes: 9,
    date: "2025-07-22",
  },
  {
    slug: "understanding-hypertension-symptoms-key-signs-you-shouldnt-ignore",
    title: "Understanding Hypertension Symptoms: Key Signs You Shouldn’t Ignore",
    href: "/blog/understanding-hypertension-symptoms-key-signs-you-shouldnt-ignore",
    image: "/images/blog/understanding-hypertension-symptoms-key-signs-you-shouldnt-ignore.png",
    specialty: "Cardiology",
    readMinutes: 4,
    date: "2025-07-22",
  },
  {
    slug: "understanding-mitral-valve-prolapse-symptoms-risks-and-management",
    title: "Understanding Mitral Valve Prolapse: Symptoms, Risks, and Management",
    href: "/blog/understanding-mitral-valve-prolapse-symptoms-risks-and-management",
    image: "/images/blog/understanding-mitral-valve-prolapse-symptoms-risks-and-management.png",
    specialty: "Cardiology",
    readMinutes: 8,
    date: "2025-07-22",
  },
  {
    slug: "understanding-2-weeks-pregnant-hcg-levels-what-you-should-know",
    title: "Understanding 2 Weeks Pregnant hcg Levels: What You Should Know",
    href: "/blog/understanding-2-weeks-pregnant-hcg-levels-what-you-should-know",
    image: "/images/blog/understanding-2-weeks-pregnant-hcg-levels-what-you-should-know.png",
    specialty: "Women's Health",
    readMinutes: 9,
    date: "2025-07-21",
  },
  {
    slug: "effective-solutions-for-pimples-from-the-heat-causes-and-prevention",
    title: "Effective Solutions for Pimples from the Heat: Causes and Prevention",
    href: "/blog/effective-solutions-for-pimples-from-the-heat-causes-and-prevention",
    image: "/images/blog/effective-solutions-for-pimples-from-the-heat-causes-and-prevention.png",
    specialty: "Women's Health",
    readMinutes: 5,
    date: "2025-07-18",
  },
  {
    slug: "understanding-knee-replacement-recovery-benefits-and-what-to-expect",
    title: "Understanding Knee Replacement: Recovery, Benefits, and What to Expect",
    href: "/blog/understanding-knee-replacement-recovery-benefits-and-what-to-expect",
    image: "/images/blog/understanding-knee-replacement-recovery-benefits-and-what-to-expect.png",
    specialty: "Orthopaedics",
    readMinutes: 8,
    date: "2025-07-18",
  },
  {
    slug: "understanding-left-arm-pain-from-shoulder-to-hand-causes-and-relief",
    title: "Understanding Left Arm Pain from Shoulder to Hand: Causes and Relief",
    href: "/blog/understanding-left-arm-pain-from-shoulder-to-hand-causes-and-relief",
    image: "/images/blog/understanding-left-arm-pain-from-shoulder-to-hand-causes-and-relief.png",
    specialty: "Orthopaedics",
    readMinutes: 9,
    date: "2025-07-18",
  },
  {
    slug: "understanding-mics-surgery-benefits-and-considerations-for-patients",
    title: "Understanding MICS Surgery: Benefits and Considerations for Patients",
    href: "/blog/understanding-mics-surgery-benefits-and-considerations-for-patients",
    image: null,
    specialty: "Cardiology",
    readMinutes: 10,
    date: "2025-06-13",
  },
  {
    slug: "essential-seizure-first-aid-what-you-need-to-know-for-emergencies",
    title: "Essential Seizure First Aid: What You Need to Know for Emergencies",
    href: "/blog/essential-seizure-first-aid-what-you-need-to-know-for-emergencies",
    image: "/images/blog/essential-seizure-first-aid-what-you-need-to-know-for-emergencies.png",
    specialty: "Neurology",
    readMinutes: 5,
    date: "2025-06-13",
  },
  {
    slug: "essential-heat-stroke-first-aid-signs-treatment-and-prevention-tips",
    title: "Essential Heat Stroke First Aid: Signs, Treatment, and Prevention Tips",
    href: "/blog/essential-heat-stroke-first-aid-signs-treatment-and-prevention-tips",
    image: "/images/blog/essential-heat-stroke-first-aid-signs-treatment-and-prevention-tips.png",
    specialty: "Neurology",
    readMinutes: 5,
    date: "2025-06-13",
  },
  {
    slug: "pimples-during-pregnancy-causes-solutions-and-effective-treatments",
    title: "Pimples During Pregnancy: Causes, Solutions, and Effective Treatments",
    href: "/blog/pimples-during-pregnancy-causes-solutions-and-effective-treatments",
    image: "/images/blog/pimples-during-pregnancy-causes-solutions-and-effective-treatments.png",
    specialty: "Women's Health",
    readMinutes: 7,
    date: "2025-06-12",
  },
  {
    slug: "why-is-my-pregnant-belly-sometimes-hard-and-sometimes-soft",
    title: "Why Is My Pregnant Belly Sometimes Hard and Sometimes Soft?",
    href: "/blog/why-is-my-pregnant-belly-sometimes-hard-and-sometimes-soft",
    image: "/images/blog/why-is-my-pregnant-belly-sometimes-hard-and-sometimes-soft.png",
    specialty: "Women's Health",
    readMinutes: 7,
    date: "2025-05-24",
  },
];

/**
 * The three posts the reference pulls out into the feature strip: the newest
 * article as the hero, then a Cardiology and a Diabetes pick beside it.
 *
 * Unlike the reference, these are NOT held out of the card grid — the grid
 * mirrors the live site's listing one-for-one, so all 100 articles appear
 * there in the same order. The strip is a highlight on top of the full list,
 * not a slice taken out of it.
 */
export const FEATURED_SLUGS: readonly string[] = [
  "sciatica-pain-treatment-understand-the-cause-and-find-the-right-relief",
  "right-side-chest-pain-what-your-symptoms-could-be-telling-you",
  "expert-diabetic-foot-care-to-keep-you-moving",
];

export const featuredPosts: BlogPost[] = FEATURED_SLUGS.map((slug) => {
  const post = blogPosts.find((p) => p.slug === slug);
  if (!post) throw new Error(`Featured post "${slug}" is not in blogPosts`);
  return post;
});

/** Post count per specialty, for deciding which filter pills to render. */
export const specialtyCounts: Record<string, number> = blogPosts.reduce<Record<string, number>>(
  (acc, p) => {
    acc[p.specialty] = (acc[p.specialty] ?? 0) + 1;
    return acc;
  },
  {},
);
