// SRM Global Hospitals - Official Press Releases Data
// Full Verbatim Content preserved from source: https://srmglobalhospitals.com/press-release/
// Every press release includes full official document text, highlights, doctor quotes & clinical details.

export interface PressReleaseItem {
  id: number;
  title: string;
  link: string;
  image: string;
  localImage: string;
  excerpt: string;
  year: "2025" | "2024";
  month: string;
  date: string;
  isoDate: string;
  category: string;
  isDocumentScan: boolean;
  highlights: string[];
  paragraphs: string[];
}

export const PRESS_RELEASES: PressReleaseItem[] = [
  {
    id: 1,
    title: "Doctor\’s Day",
    link: "https://srmglobalhospitals.com/event/doctors-day/",
    image: "https://srmglobalhospitals.com/wp-content/uploads/2025/11/Doctors-Day-July-20205-724x1024.jpg",
    localImage: "/images/press-releases/Doctors-Day-July-20205-724x1024.jpg",
    excerpt: "",
    year: "2025",
    month: "November",
    date: "July 1, 2025",
    isoDate: "2025-11-17T12:23:32+00:00",
    category: "Community & Awareness",
    isDocumentScan: true,
    highlights: [
    ],
    paragraphs: [
    ],
  },
  {
    id: 2,
    title: "Rare Double Uterus",
    link: "https://srmglobalhospitals.com/event/rare-double-uterus/",
    image: "https://srmglobalhospitals.com/wp-content/uploads/2025/11/Rare-Double-Uterus-June-2025-724x1024.jpg",
    localImage: "/images/press-releases/Rare-Double-Uterus-June-2025-724x1024.jpg",
    excerpt: "",
    year: "2025",
    month: "November",
    date: "June 2025",
    isoDate: "2025-11-17T12:14:07+00:00",
    category: "Clinical Milestone",
    isDocumentScan: true,
    highlights: [
    ],
    paragraphs: [
    ],
  },
  {
    id: 3,
    title: "SRM Global Hospitals Performs Rare Double Shoulder Surgery with Stem Cells on 52-Year-Old Volleyball Coach",
    link: "https://srmglobalhospitals.com/event/srm-global-hospitals-performs-rare-double-shoulder-surgery-with-stem-cells-on-52-year-old-volleyball-coach/",
    image: "https://srmglobalhospitals.com/wp-content/uploads/2025/11/Stemcell-52-Year-Old-1-Page-724x1024.jpg",
    localImage: "/images/press-releases/Stemcell-52-Year-Old-1-Page-724x1024.jpg",
    excerpt: "",
    year: "2025",
    month: "November",
    date: "November 2025",
    isoDate: "2025-11-17T12:07:06+00:00",
    category: "Surgical Excellence",
    isDocumentScan: true,
    highlights: [
    ],
    paragraphs: [
    ],
  },
  {
    id: 4,
    title: "SRM Global Hospital\’s New Aortic Centre Saves 30-Year-Old in Rare Hybrid Surgery",
    link: "https://srmglobalhospitals.com/event/srm-global-hospitals-new-aortic-centre-saves-30-year-old-in-rare-hybrid-surgery/",
    image: "https://srmglobalhospitals.com/wp-content/uploads/2025/11/New-Aortic-30-Year-Old-1-Page-724x1024.jpg",
    localImage: "/images/press-releases/New-Aortic-30-Year-Old-1-Page-724x1024.jpg",
    excerpt: "",
    year: "2025",
    month: "November",
    date: "November 2025",
    isoDate: "2025-11-17T11:58:00+00:00",
    category: "Surgical Excellence",
    isDocumentScan: true,
    highlights: [
    ],
    paragraphs: [
    ],
  },
  {
    id: 5,
    title: "Advanced Laser Surgery at SRM Global Hospitals Restores Urinary Function in Iraqi Senior Citizen with High-Risk Cardiac Condition",
    link: "https://srmglobalhospitals.com/event/advanced-laser-surgery-at-srm-global-hospitals-restores-urinary-function-in-iraqi-senior-citizen-with-high-risk-cardiac-condition/",
    image: "https://srmglobalhospitals.com/wp-content/uploads/2025/11/srm_pix1-1024x770.jpeg",
    localImage: "/images/press-releases/srm_pix1-1024x770.jpeg",
    excerpt: "Advanced Laser Surgery at SRM Global Hospitals Restores Urinary Function in Iraqi Senior Citizen with High-Risk Cardiac Condition Benign Prostatic Enlargement affects 50\–60% of men above 60, making it a leading urological condition HoLEP, a minimally invasive laser surgery, enables precise tissue removal with minimal bleeding and quick recovery Chennai, November xx 2025: SRM Global ...",
    year: "2025",
    month: "November",
    date: "November 13, 2025",
    isoDate: "2025-11-13T04:38:29+00:00",
    category: "Surgical Excellence",
    isDocumentScan: false,
    highlights: [
      "Benign Prostatic Enlargement affects 50–60% of men above 60, making it a leading urological condition.",
      "HoLEP, a minimally invasive laser surgery, enables precise tissue removal with minimal bleeding and quick recovery.",
    ],
    paragraphs: [
      "Chennai, November 13, 2025: SRM Global Hospitals successfully restored urinary function in a 74-year-old male patient from Iraq who was suffering from obstructive urinary symptoms caused by Benign Prostatic Enlargement (BPE), a non-cancerous increase in the size of the prostate gland that commonly affects elderly men. Taking into account the patient’s severe coronary artery disease and his dependence on blood-thinning medication, the urology team opted for advanced holmium laser technology for the removal of the enlarged prostate tissue, thereby avoiding the risks associated with conventional invasive surgical procedures.",
      "The procedure, known as Holmium Laser Enucleation of the Prostate (HoLEP), is an advanced, minimally invasive laser surgery technique. Unlike Transurethral Resection of the Prostate (TURP), which is the conventional gold standard, HoLEP offers significant advantages, including minimal bleeding, shorter hospital stay, and faster recovery.",
      "The surgical team was led by Dr. Anand Krishnamoorthy and Dr. M. Deepak, Senior Consultant Urologists, supported by Dr. Varun C., Senior Consultant Anaesthetist. Dr. T. R. Muralidharan, Cardiologist, conducted the pre-surgical cardiac evaluation and formulated the cardiac management plan.",
      "In his comments, Dr. P. Sathyanarayanan, President, SRM Global hospitals, said, “Advanced urological procedures like HoLEP represent the technological and clinical progress now taking place at SRM Global Hospitals, where it was successfully performed on a severely cardiac-compromised patient. The surgery used advanced holmium laser technology under continuous monitoring and required coordinated support from a multidisciplinary team. Despite a high risk of on-table heart attack, the procedure was completed safely through meticulous pre-operative planning and intra-operative management. This case highlights the precision and collaboration involved – the urologists performed the HoLEP procedure, the cardiologists oversaw pre- and post-operative cardiac care, the anesthesiologists ensured real-time stabilisation, and the ICU team provided diligent postoperative monitoring. The case validates SRM Global Hospitals’ commitment to delivering safe, advanced care in challenging scenarios.”",
      "In his comments, Dr. Anand Krishnamoorthy said, “The patient from Iraq arrived with severe urinary issues. Tests showed elevated PSA levels, prompting an MRI and biopsy that confirmed benign prostate enlargement, ruling out cancer. During pre-surgical evaluation, we found severe cardiac blockages. Although cardiac intervention was advised first, the patient wished to proceed with prostate surgery so he could resume prayers without urinary difficulty. With careful pre-surgical preparation and advanced cardiac monitoring, we safely performed Holmium Laser Enucleation of the Prostate (HoLEP). The minimally invasive laser procedure allowed precise tissue removal with minimal bleeding and a fast recovery. The patient responded well, was discharged in stable condition, and remains symptom-free under regular follow-up.”",
      "Talking about BPE and its causes, Dr Anand said that this condition affects nearly 50–60% of men above 60 years of age, making it one of the most common urological conditions in elderly men. It occurs primarily due to age-related hormonal changes that cause the prostate tissue to grow. Common warning signs include frequent urination at night, weak urine flow, straining during urination, or a feeling of incomplete bladder emptying. These symptoms should not be ignored, as timely diagnosis and treatment can prevent the condition from progressing to severe obstruction that might require surgical intervention. “Men above the age of 50 should undergo regular health check-ups and seek early medical consultation if they experience urinary difficulties. Maintaining optimal blood pressure, blood sugar, and cholesterol levels also helps reduce the risk of prostate-related complications.”",
    ],
  },
  {
    id: 6,
    title: "SRM Global Hospitals Successfully Conducts a Rare Kidney Transplant Between a Donor and Recipient with Mismatched Blood Groups",
    link: "https://srmglobalhospitals.com/event/srm-global-hospitals-successfully-conducts-a-rare-kidney-transplant-between-a-donor-and-recipient-with-mismatched-blood-groups/",
    image: "https://srmglobalhospitals.com/wp-content/uploads/2025/08/ABO-Nephro-Case.png",
    localImage: "/images/press-releases/ABO-Nephro-Case.png",
    excerpt: "The complexity of the ABO-incompatible transplant, where the father was the donor and the son the recipient, was further heightened by the patient\’s elevated antibody levels. The procedure was successfully carried out using advanced immunoadsorption therapy, which effectively reduced the risk of rejection. Chennai, 31 July 2025: SRM Global Hospitals successfully performed a high-risk ABO-incompatible ...",
    year: "2025",
    month: "November",
    date: "July 31, 2025",
    isoDate: "2025-08-29T08:24:55+00:00",
    category: "Surgical Excellence",
    isDocumentScan: false,
    highlights: [
      "The complexity of the ABO-incompatible transplant, where the father was the donor and the son the recipient, was further heightened by elevated antibody levels.",
      "The procedure was successfully carried out using advanced immunoadsorption therapy, effectively reducing the risk of organ rejection.",
    ],
    paragraphs: [
      "Chennai, 31 July 2025: SRM Global Hospitals successfully performed a high-risk ABO-incompatible kidney transplant, a procedure involving a donor and recipient with different blood types, on a 28-year-old former IT professional who had been on dialysis for over three years after his kidneys failed due to an autoimmune condition. To minimise the risk of rejection of the transplanted kidney, which was donated by his father, the hospital employed a specialised procedure called immunoadsorption to significantly lower the patient’s antibody levels to within the standard safety threshold at the time of the transplant. The patient is now recovering well and has transitioned from dialysis to oral immunosuppressive therapy for ongoing management.",
      "The patient, Joseph Raj, from Chennai, was diagnosed with IgA nephropathy, a chronic kidney disease in which the immune system produces antibodies that mistakenly attack the kidneys, often due to genetic factors. The disease led to end-stage renal failure, forcing him to quit his job and undergo dialysis three times a week for the past three years. In the absence of a compatible donor, Joseph’s father, who is A positive, volunteered to donate his kidney, although Joseph’s blood group is O positive. This mismatch made it an ABO-incompatible transplant, a procedure associated with high risk due to the presence of naturally occurring antibodies in the recipient’s blood that can attack the donor kidney. These antibody levels, known as titer levels, reflect the strength of the immune response. A titer above 1:512 indicates a high concentration of antibodies, which can aggressively attack the donor kidney and increase the risk of rejection. However, the patient’s titer level was significantly high, around 1:1024.",
      "Considering the complexity of the case, the hospital initiated a unique desensitisation protocol 14 days prior to the ABO-incompatible transplant. This included the use of immunoadsorption, a specialised procedure that selectively removes harmful antibodies from the blood. The process successfully reduced the antibody titer to a safe level of 1:8 approximately 24 hours before the surgery. The transplant was then carried out, followed by close postoperative monitoring. When antibody titers spiked again, a second immunoadsorption session was promptly administered. The patient was discharged on the eighth day in stable condition, with a normal creatinine level of 1.1—an encouraging indicator of healthy kidney function.",
      "Post-surgery, Joseph Raj responded well to immunosuppressive therapy and was discharged in excellent spirits, marking a remarkably swift recovery period. He is currently under regular follow-up and immunosuppressant therapy. His post-surgery plan includes following a healthy lifestyle, infection control, and routine checkups. He is expected to lead a normal life and can eventually resume work.",
      "The transplant team was headed by Dr. Mathew Gerry George, Senior Consultant Nephrologist, and Dr. Deepak, Consultant Urologist and Transplant Surgeon. In his comments, Dr. P. Sathyanarayanan, President of SRM Global Hospitals, said, “This extraordinary case stands as a testament to the clinical excellence and speed of execution demonstrated by our transplant team. Managing such a complex protocol within a tight timeline is a matter of immense pride for us. With ABO-incompatible transplants, patients no longer have to wait for the same blood group match, as it expands the donor pool vastly. We are proud to join the list of few hospitals performing such transplants successfully and safely, promising a fresh start to the patient.”",
      "Talking about the surgery, Dr. Mathew Gerry George, Senior Consultant Nephrologist, SRM Global Hospitals, said, “The goal of a kidney transplant is to improve the quality of life of a patient. This case is significant because we incorporated ABO-incompatible transplant, which was once considered high-risk and near-impossible beyond certain titer limits, and is now within reach with the right expertise and infrastructure. This milestone is now a convenient and reliable solution for patients with willing but non-matching donors. This development opens new avenues for kidney patients who were previously limited by blood group constraints, significantly increasing the donor pool and improving their quality of life.”",
    ],
  },
  {
    id: 7,
    title: "SRM Global Hospitals Performs Laparoscopic Hernia Surgery on 90-Year-Old Patient",
    link: "https://srmglobalhospitals.com/event/srm-global-hospitals-performs-laparoscopic-hernia-surgery-on-90-year-old-patient/",
    image: "https://srmglobalhospitals.com/wp-content/uploads/2024/08/srm-our-culture-img1.png",
    localImage: "/images/press-releases/srm-our-culture-img1.png",
    excerpt: "The patient, with a 30-year history of hypertension and coronary artery disease under medication, had undergone hernia surgery 40 years ago. Elderly patients can benefit from laparoscopy if peri-operative optimisation is done well to prevent complications and reduce surgery time. Chennai, May 27, 2025: SRM Global Hospitals successfully performed laparoscopic surgery to treat inguinal hernia ...",
    year: "2025",
    month: "November",
    date: "May 27, 2025",
    isoDate: "2025-08-29T07:12:00+00:00",
    category: "Surgical Excellence",
    isDocumentScan: false,
    highlights: [
      "The patient, with a 30-year history of hypertension and coronary artery disease under medication, had undergone hernia surgery 40 years ago.",
      "Elderly patients can benefit from laparoscopy if peri-operative optimisation is done well to prevent complications and reduce surgery time.",
    ],
    paragraphs: [
      "Chennai, May 27, 2025: SRM Global Hospitals successfully performed laparoscopic surgery to treat inguinal hernia in a 90-year-old lady with co-morbidities including hypertension and coronary artery disease. The hospital’s expertise and effective peri-operative care ensured a smooth procedure. Admitted in an emergency, the patient was discharged in stable condition on the third day and walked out on her own.",
      "A hernia is a condition where an internal organ or tissue pushes through a weak spot in the surrounding muscle or connective tissue, often forming a visible lump or bulge. An inguinal hernia occurs in the groin area.",
      "Laparoscopic surgery is a well-established approach for treating most abdominal and pelvic conditions in older adults. It offers clear benefits such as minimal surgical trauma, faster recovery, and shorter hospital stays. With skilled surgeons, modern facilities, and strong peri-operative support, outcomes in elderly patients can be significantly improved.",
      "The surgical team was led by Dr. Sugi Subramaniam, Senior Consultant in Gastrointestinal Surgery, HPB Surgery, and Liver Transplant, supported by expert anesthetists. The peri-operative assessment and optimisation involved a multidisciplinary team, including cardiologists, to ensure the patient was fully prepared for surgery.",
      "Explaining the case, Dr. Sugi Subramaniam said: “A 90-year-old woman presented with a one-month history of swelling in the right groin, which initially reduced on lying down but later became persistent and painful. She had systemic hypertension and coronary artery disease for 30 years, and had undergone left-sided open inguinal hernia repair 40 years ago. Evaluation revealed bilateral inguinal hernias with small bowel loops as contents—both direct and indirect on the right, and direct on the left.”",
      "He added: “After careful assessment of her general and cardiac fitness, she was deemed suitable for surgery and underwent bilateral trans-abdominal preperitoneal (TAPP) mesh repair, a minimally invasive laparoscopic procedure. Postoperatively, she was monitored in the ICU and then shifted to the ward. Oral intake was resumed on day one, and she recovered well. She was discharged in stable condition on postoperative day three and is doing well on follow-up.”",
      "Dr. P. Sathyanarayanan, President, SRM Global Hospitals, remarked: “With remarkable advancements in medical and surgical care, more people are living well into their 80s and beyond. As life expectancy increases, elderly patients often present with surgical needs—both elective and emergency—sometimes with added risks due to age-related decline. However, procedures like geriatric laparoscopic surgery offer a transformative solution. By combining careful peri-operative assessment, surgical precision, and focused post-operative care, we can minimise trauma and accelerate recovery in this vulnerable population. At SRM Global Hospitals, we strive to extend and improve quality of life in our aging population through teamwork, planning, and the power of minimally invasive techniques.”",
    ],
  },
  {
    id: 8,
    title: "SRM Global Hospitals Hosts SPACE 2025 to Advance Electrophysiology and Arrhythmia Treatment in India",
    link: "https://srmglobalhospitals.com/event/srm-global-hospitals-hosts-space-2025-to-advance-electrophysiology-and-arrhythmia-treatment-in-india/",
    image: "https://srmglobalhospitals.com/wp-content/uploads/2025/08/Space-2025.png",
    localImage: "/images/press-releases/Space-2025.png",
    excerpt: "Top cardiologists, including Dr. Samuel J. Asirvatham of Mayo Clinic, and Dr. C. Narasimhan of AIG Hospital, bring global perspectives and best practices Chennai, March 16, 2025: SRM Global Hospitals organised SPACE 2025 \– SRM\’s Pacing and Clinical Electrophysiology Conference, a two-day event held on March 15\–16 that brought together over 100 cardiologists from across ...",
    year: "2025",
    month: "November",
    date: "March 16, 2025",
    isoDate: "2025-08-29T07:09:54+00:00",
    category: "Conference & Events",
    isDocumentScan: false,
    highlights: [
      "Top cardiologists, including Dr. Samuel J. Asirvatham of Mayo Clinic, and Dr. C. Narasimhan of AIG Hospital, bring global perspectives and best practices.",
      "SRM's Pacing and Clinical Electrophysiology Conference brought together over 100 cardiologists from across the country.",
    ],
    paragraphs: [
      "Chennai, March 16, 2025: SRM Global Hospitals organised SPACE 2025 – SRM’s Pacing and Clinical Electrophysiology Conference, a two-day event held on March 15–16 that brought together over 100 cardiologists from across India to explore the latest advancements in electrophysiology and arrhythmia management.",
      "SPACE 2025 featured eminent international experts such as Dr. Samuel J. Asirvatham from the Mayo Clinic, Minnesota, and Dr. C. Narasimhan from AIG Hospital, Hyderabad. These global luminaries, along with leading Indian specialists, delivered insightful lectures and engaged in complex case discussions, greatly enriching the knowledge base of participants.",
      "Commenting on the event, Dr. P. Sathyanarayanan, President, SRM Global Hospitals, said: “SPACE 2025 aims to elevate the standard of cardiac care in India by convening experts and practitioners, enabling knowledge-sharing and the exploration of innovative technologies. Our hospital is committed to improving outcomes for patients with arrhythmias or irregular heartbeats that have become a significant health concern in India. Atrial fibrillation (AF), the most common type, impacts approximately 33 million individuals globally and is a leading cause of stroke, heart failure, and other cardiovascular complications. In India, anywhere from 2 to 4 million individuals are living with AF.”",
      "Dr. T. R. Muralidharan, Organising Chairman of SPACE 2025 and Director of the Institute of Cardiac Sciences at SRM Global Hospitals, explained that the conference was organised to foster collaboration and disseminate cutting-edge knowledge, ultimately contributing to the advancement of cardiac care in India.",
      "He further noted: “Although the prevalence of AF across different Indian demographics is relatively lower compared to Western countries, with an aging population and increasing prevalence of risk factors like hypertension and diabetes, the burden of AF in India is expected to rise. In this context, platforms like SPACE play a crucial role in enhancing awareness, early detection, and effective management strategies.”",
    ],
  },
  {
    id: 9,
    title: "3-Day-Old Baby Born with One Lung Gets a New Lease on Life at SRM Global Hospitals after Rare Surgery",
    link: "https://srmglobalhospitals.com/event/3-day-old-baby-born-with-one-lung-gets-a-new-lease-on-life-at-srm-global-hospitals-after-rare-surgery/",
    image: "https://srmglobalhospitals.com/wp-content/uploads/2025/08/3-Day-Old-Bbaby.png",
    localImage: "/images/press-releases/3-Day-Old-Bbaby.png",
    excerpt: "The baby was diagnosed with a left diaphragmatic hernia while in the mother\’s womb Surgery was meticulously planned in advance, including complex anesthesia management Post-surgery, the child has a high chance of leading a normal life Chennai, March 4, 2025: In a rare medical achievement, a team of doctors at SRM Global Hospitals successfully performed ...",
    year: "2025",
    month: "November",
    date: "March 4, 2025",
    isoDate: "2025-08-29T07:04:20+00:00",
    category: "Surgical Excellence",
    isDocumentScan: false,
    highlights: [
      "The baby was diagnosed with a left diaphragmatic hernia while in the mother’s womb.",
      "Surgery was meticulously planned in advance, including complex anesthesia management.",
      "Post-surgery, the child has a high chance of leading a normal, healthy life.",
    ],
    paragraphs: [
      "Surgery was meticulously planned in advance, including complex anesthesia management Post-surgery, the child has a high chance of leading a normal life",
      "Chennai, March 4, 2025: In a rare medical achievement, a team of doctors at SRM Global Hospitals successfully performed a complex surgical procedure called thoracoscopic meshplasty on a three-day-old baby diagnosed with congenital left diaphragmatic hernia. Following the successful minimally invasive thoracoscopic surgery, the baby made a full recovery and was discharged within a week.",
      "A routine prenatal scan had revealed a deformity in the baby’s diaphragm—the membrane that separates the chest cavity from the abdomen. The birth defect created a hole in the diaphragm, allowing abdominal organs such as the stomach, intestines, and liver to move into the chest. This severely compressed the lungs and heart, making it difficult for the baby to breathe. The child was born with only one functional lung, which was underdeveloped and compromised.",
      "Recognizing the critical nature of the condition, Dr. M. Saravana Balaji and Dr. N. Prathiba, Pediatric Surgeons at SRM Global Hospitals, meticulously planned the life-saving surgery even before birth. At delivery, Dr. Prithiv Raj oversaw the procedure and ensured immediate intubation, while Dr. C. Ashok managed stabilization in the Neonatal ICU. On the third day of life, the baby underwent thoracoscopic meshplasty. The anesthesia team, led by Dr. Varun Chellapandi and Dr. Priyadharshini Sampath, played a crucial role in managing the high-risk anesthesia requirements.",
      "The minimally invasive surgery involved making a small incision to push the displaced abdominal organs back into the abdomen. A surgical mesh was then placed to reinforce the diaphragm, enabling the chest organs to develop properly. The baby recovered remarkably well and was discharged in stable condition within a week.",
      "Dr. P. Sathyanarayanan, President of SRM Group, praised the team, stating: “Advancements in diagnostics, critical care, and minimally invasive surgery have made complex neonatal surgeries like this possible. The seamless coordination between our antenatal, neonatal, and surgical teams played a pivotal role in achieving this successful outcome. At the end of the day, we are glad and happy to have helped the child go on and lead a normal life.”",
      "Reflecting on the case, Dr. Saravana Balaji and Dr. Prathiba added: “Successfully performing thoracoscopic meshplasty on a newborn with such a large defect is a significant achievement. This minimally invasive approach allowed us to repair the diaphragm with minimal disruption, ensuring better recovery. The baby’s remarkable progress underscores the effectiveness of this well-planned teamwork.”",
    ],
  },
  {
    id: 10,
    title: "SRM Global Hospitals Launches WOW, a Centre Exclusively for Women\’s Health and Wellness",
    link: "https://srmglobalhospitals.com/event/srm-global-hospitals-launches-wow-a-centre-exclusively-for-womens-health-and-wellness/",
    image: "https://srmglobalhospitals.com/wp-content/uploads/2025/08/Wow-Launch.png",
    localImage: "/images/press-releases/Wow-Launch.png",
    excerpt: "WOW houses advanced medical and rehabilitative facilities with a special focus on pregnancy and post-pregnancy wellness To introduce an all-inclusive package for delivery, covering all scans, tests, yoga, nutrition, and pregnancy-related complications. Chennai, 18 February 2025: SRM Global Hospitals has launched the Centre for Women\’s Health & Wellness \– WOW, to provide comprehensive, high-quality, and ...",
    year: "2025",
    month: "November",
    date: "February 18, 2025",
    isoDate: "2025-08-29T07:01:55+00:00",
    category: "Centre Launch",
    isDocumentScan: false,
    highlights: [
      "WOW houses advanced medical and rehabilitative facilities with a special focus on pregnancy and post-pregnancy wellness.",
      "Introduces an all-inclusive package for delivery, covering all scans, tests, yoga, nutrition, and pregnancy-related care.",
    ],
    paragraphs: [
      "To introduce an all-inclusive package for delivery, covering all scans, tests, yoga, nutrition, and pregnancy-related complications.",
      "Chennai, 18 February 2025: SRM Global Hospitals has launched the Centre for Women’s Health & Wellness – WOW, to provide comprehensive, high-quality, and patient-focused medical services, ensuring that women receive exceptional care at every stage of life.",
      "The centre was inaugurated by Ms. Manimangai Sathyanarayanan, Managing Director, SRM Global Hospitals, in the presence of Dr. V.P. Chandrasekaran, Chief Operating Officer of the hospital. The dignitaries who took part in the inaugural function included Dr. T. Mythili, Additional Registrar, SRM Institute of Science and Technology; Dr. Nitin M. Nagarkar, Pro Vice Chancellor (Medical); Dr. R. Venkatraman, Medical Superintendent, SRM Medical College Hospital; Dr. R. Swaminathan, Clinical Superintendent; and Dr. Saswati Tripaty, Senior Consultant, Obstetrics & Gynecology, SRM Global Hospitals.",
      "In her remarks, Ms. Manimangai Sathyanarayanan, Managing Director, SRM Global Hospitals, said, “WOW is designed as a one-stop destination for all women’s health needs, offering advanced facilities and expert medical care. To ensure a seamless and stress-free maternity experience, we have kept all essential facilities—OP ward, lab, and labor room—on the same floor. With specialists readily available nearby, patients never have to step out for tests, consultations, or any other requirement. WOW houses world-class amenities to ensure comfortable, safe, and advanced healthcare for every patient.”",
      "The centre is equipped with modern labor and delivery rooms, maternity wards, a neonatal intensive care unit (NICU), fertility clinics, ultrasound and imaging facilities, gynecological operating theaters, breast health and screening units, fertility consultation and counseling rooms, emergency and trauma care, as well as physiotherapy and pelvic floor rehabilitation services. The multidisciplinary team includes Gynecologists, Obstetricians, Maternal-fetal medicine specialists, Dermatologists, and Pelvic floor Therapists, supported by Nutritionists/Dietitians, Lactation specialists, and Yoga experts.",
      "Speaking on the focus of the healthcare services provided by WOW, Dr. Saswati Tripathi, Senior Consultant—Obstetrics & Gynaecology, said, “At the core of our mission is holistic maternal and reproductive healthcare, focusing on both pregnancy and post-pregnancy wellness. With a team of renowned Obstetricians and Gynaecologists, the hospital is committed to providing personalized treatment plans, high-risk pregnancy management, fertility solutions, and postpartum care. The initiative emphasizes maternal well-being, neonatal safety, and overall women’s health, ensuring a seamless journey from conception to motherhood and beyond.”",
      "She further highlighted that the hospital follows a transparent pricing model with a fixed fee for delivery—whether normal or cesarean—covering all scans, tests, yoga, and nutrition sessions throughout the nine-month journey. Any pregnancy-related complications are also included in this cost, ensuring comprehensive care without unexpected expenses.",
      "With the launch of WOW – Centre for Women’s Health & Wellness, SRM Global Hospitals reaffirms its commitment to setting new standards in women’s healthcare, combining clinical excellence with compassionate care.",
    ],
  },
  {
    id: 11,
    title: "SRM Global Hospitals Removes Rare Diaphragm Tumor Weighing 1.2kg from 78-Year-Old Woman",
    link: "https://srmglobalhospitals.com/event/srm-global-hospitals-removes-rare-diaphragm-tumor-weighing-1-2kg-from-78-year-old-woman/",
    image: "https://srmglobalhospitals.com/wp-content/uploads/2025/08/78-Year-Old-Case-Image.png",
    localImage: "/images/press-releases/78-Year-Old-Case-Image.png",
    excerpt: "While tumors in the diaphragm within the abdominal region are relatively common, a diaphragm tumor within the chest cavity is extremely rare. The procedure also involved removing part of the diaphragm to minimise the risk of recurrence. Chennai, 10 January 2024: SRM Global Hospitals successfully saved the life of a 78-year-old former nurse by removing ...",
    year: "2024",
    month: "November",
    date: "January 10, 2024",
    isoDate: "2025-08-29T07:00:07+00:00",
    category: "Surgical Excellence",
    isDocumentScan: false,
    highlights: [
      "While tumors in the diaphragm within the abdominal region are relatively common, a diaphragm tumor within the chest cavity is extremely rare.",
      "The procedure also involved removing part of the diaphragm to minimise the risk of recurrence.",
    ],
    paragraphs: [
      "Chennai, 10 January 2024: SRM Global Hospitals successfully saved the life of a 78-year-old former nurse by removing a ‘football-sized’ diaphragm tumor, overcoming significant surgical challenges posed by the tumor’s location within the chest cavity, the patient’s advanced age, and comorbidities, including type-2 diabetes and chronic kidney disease.",
      "Several months ago, the woman, a known cancer patient, underwent surgery at another hospital where her tumor was partially removed. However, following the procedure, the tumor grew rapidly, compressing her right lung and displacing her heart and other vital organs further to the left within the chest cavity. By the time she was admitted to SRM Global Hospitals with severe shortness of breath, the tumor had expanded to a humongous size of 15 x 15 x 15 cm.",
      "The surgical procedure, led by Dr. Sujith Velayudhan Indira, Senior Consultant in Cardiothoracic Surgery, and assisted by Dr. Srinath, Cardiac Anaesthetist; Dr. B. Nembian Raja Rajan, Assistant Consultant in Cardiothoracic Surgery; and Dr. Sindhu V., Consultant in Pulmonology, successfully resulted in the complete removal of the tumor. The patient was discharged six days after the surgery but will undergo radiation therapy over the coming months as a precautionary measure to eliminate any undetected microscopic remnants of the tumor.",
      "Talking about the treatment, Dr. Sujith Velayudhan Indira explained, “The patient had developed a giant right-sided intra-thoracic mass at the diaphragm within the chest cavity. The tumor was so large that it compressed and collapsed the lower lobe of the right lung while pushing the heart and other vital organs further to the left. This led to the development of dyspnoea (shortness of breath). While tumors in the diaphragm within the abdominal region are relatively common, a diaphragm tumor within the chest cavity is extremely rare and has not been reported in the literature so far. Additionally, the patient had a known history of type-2 diabetes and chronic kidney disease, which made the surgery even more challenging.”",
      "Dr. P. Sathyanarayanan, President of SRM Group of Companies, commended the team for their remarkable achievement, saying, “Conducting surgery in the highly vascular chest cavity itself is risky. However, our team successfully accomplished what is inherently a challenging procedure. It was a tremendous team effort and yet another demonstration of our expertise in taking on high-risk operations when absolutely necessary to save a life and enhance the quality of life. The patient, being a former nurse, showed full courage and cooperated wholeheartedly with the treatment.”",
      "About SRM Global Hospitals: SRM Global Hospitals is a leading healthcare institution dedicated to providing world-class medical services with an unwavering commitment to innovation, patient care, and excellence. Equipped with state-of-the-art facilities, the hospital operates 24/7 with advanced radiology imaging, super-specialty care, and 200+ AI-enabled beds.",
      "With a multidisciplinary team of over 100 expert doctors and a comprehensive range of 30+ medical specialties, SRM Global Hospitals also boasts 10+ Centers of Excellence, ensuring exceptional care for diverse healthcare needs. Our mission is to redefine healthcare standards by blending compassionate care with cutting-edge treatment methodologies to ensure the well-being of every patient.",
    ],
  },
  {
    id: 12,
    title: "SRM Global Hospitals Successfully Treats India\’s First Case of Heart Cavity Lump with Keyhole Surgery",
    link: "https://srmglobalhospitals.com/event/srm-global-hospitals-successfully-treats-indias-first-case-of-heart-cavity-lump-with-keyhole-surgery/",
    image: "https://srmglobalhospitals.com/wp-content/uploads/2025/08/heart-care.webp",
    localImage: "/images/press-releases/heart-care.webp",
    excerpt: "Globally, only about ten cases of the cyst inside the pericardium have been reported in the published literature so far. The medical team successfully avoided intensive procedures that would have required stopping the heart and lung functions. Chennai, 18 December 2024: A 50-year-old woman from Puducherry became the first patient to be treated for a ...",
    year: "2024",
    month: "December",
    date: "December 18, 2024",
    isoDate: "2025-08-29T05:54:01+00:00",
    category: "Surgical Excellence",
    isDocumentScan: false,
    highlights: [
      "Globally, only about ten cases of the cyst inside the pericardium have been reported in the published medical literature so far.",
      "The medical team successfully avoided intensive procedures that would have required stopping the heart and lung functions.",
    ],
    paragraphs: [
      "Chennai, 18 December 2024: A 50-year-old woman from Puducherry became the first patient to be treated for a cyst, a lump, inside the pericardium, the double-layered sac around the heart. The milestone was achieved recently at SRM Global Hospitals, where the medical team successfully performed a keyhole surgery to remove the giant mass – measuring around 8 x 8 x 5 cm, occupying the whole of the pericardial cavity, avoiding the need for intensive procedures that usually involve stopping the heart and lung functions. Thanks to this minimally invasive approach, the patient was discharged just a few days after the procedure, marking a swift and remarkable recovery.",
      "The medical team, led by Dr. Sujith Velayudhan Indira, Senior Consultant in Cardiothoracic Surgery, included Dr. Sreenath, Cardiac Anaesthetist, Dr. B. Nembian Raja Rajan, Assistant Consultant in Cardiothoracic Surgery, and Dr. Sindhu V., Consultant in Pulmonology.",
      "In his remarks about this achievement, Dr. P. Sathyanarayanan, President of SRM Group of Companies, highlighted the rarity and significance of the case. “Cysts within the pericardial cavity are extremely uncommon, with only a handful of cases documented globally in medical literature. This underscores the uniqueness of the condition, and the importance of the successful treatment carried out at SRM Global Hospitals. The minimally invasive approach stands out because it has eliminated the need for more invasive procedures, which typically require temporarily halting the functions of the heart and lungs – a high-risk process. This accomplishment not only marks a milestone in the hospital’s medical expertise but also sets a benchmark for treating similar rare conditions with less-invasive techniques, ensuring better outcomes and faster recovery times for patients.”",
      "Sharing the patient’s journey, Dr. Sujith Velayudhan Indira said that the 50-year-old woman from Puducherry had been experiencing a persistent cough and difficulty breathing for several weeks. A scan at a local hospital revealed a large cyst in her chest, pressing against the left atrium of the heart. A detailed CT scan confirmed that the growth was dangerously close to major blood vessels, the left atrium, and pulmonary veins.",
      "“After further evaluation at SRM Global Hospitals, we decided on a minimally invasive procedure known as a right-sided mini thoracotomy, which involved making a small 6 cm incision. During the surgery, we discovered that the cyst was even more complex than anticipated. It measured approximately 8 x 8 x 5 cm and had completely filled the space around the heart, wrapping around major blood vessels and nestled between critical areas such as the right pulmonary artery and the roof of the left atrium, even extending to the tip of the heart’s left atrial appendage.”",
      "On the treatment approach, he added that to treat the cyst, the team used a procedure called marsupialization. This involved carefully opening the cyst, draining its contents, and stitching its edges to nearby tissue to prevent recurrence. “Remarkably, we avoided using a heart-lung machine, which would have required stopping the patient’s heart and lungs during the operation. The patient recovered well after the surgery. Her recovery was smooth, and she was able to return home just four days after the procedure.”",
      "A biopsy later confirmed that the cyst was benign, likely a bronchogenic cyst, a non-cancerous growth that develops during early life. This case highlights the success of minimally invasive techniques in handling even the most challenging medical conditions.",
    ],
  },
  {
    id: 13,
    title: "SRM Global Hospitals Treats 7-Year-Old Boy from Jharkhand for Rare Bone Tumor",
    link: "https://srmglobalhospitals.com/event/srm-global-hospitals-treats-7-year-old-boy-from-jharkhand-for-rare-bone-tumor/",
    image: "https://srmglobalhospitals.com/wp-content/uploads/2025/08/7-Year-Old-Bone-Tumor.png",
    localImage: "/images/press-releases/7-Year-Old-Bone-Tumor.png",
    excerpt: "Osteoid osteoma ranks as the third most common benign bone tumor in children, with an occurrence rate of 1 in 1,00,000. The surgery was challenging due to the tumor\’s tiny size, measuring just 5 mm x 5 mm, and its location deep within the shaft of the boy\’s upper arm bone. Chennai, 3 December 2024: ...",
    year: "2024",
    month: "December",
    date: "December 3, 2024",
    isoDate: "2025-08-29T05:53:29+00:00",
    category: "Surgical Excellence",
    isDocumentScan: false,
    highlights: [
      "Osteoid osteoma ranks as the third most common benign bone tumor in children, with an occurrence rate of 1 in 1,00,000.",
      "The surgery was challenging due to the tumor’s tiny size, measuring just 5 mm x 5 mm, and its location deep within the upper arm bone.",
    ],
    paragraphs: [
      "The surgery was challenging due to the tumor’s tiny size, measuring just 5 mm x 5 mm, and its location deep within the shaft of the boy’s upper arm bone.",
      "Chennai, 3 December 2024: SRM Global Hospital successfully treated a 7-year-old boy from Jharkhand for a rare bone tumor using advanced surgical techniques. The tumor, identified as Intra-cortical Osteoid osteoma, is a benign yet highly painful condition that occurs in only one out of one lakh children. For four months, the boy suffered from persistent and severe pain in his right arm. However, after the surgery, he was completely relieved of pain and symptoms.",
      "Measuring just 5 mm x 5 mm, the tumor was deeply embedded in the shaft of the boy’s humerus (upper arm bone). Despite its small size, it caused intense discomfort, particularly at night, disrupting his sleep. It was not possible for him to carry out his daily routines like writing, carrying objects, and playing. The boy also required regular use of painkillers.",
      "An expert surgical team led by Dr. B. Vijay Anand, Orthopaedic Consultant, performed a complex procedure called the Burr Down Technique to remove the tumor. To ensure precision, the tumor location was marked using a multiple-needle technique under CT guidance. During surgery, an image intensifier machine provided real-time imaging, helping the team overcome the challenge of locating the tiny tumor within the bone.",
      "Dr. Vijay Anand explained, “What makes this surgery unique is the tiny size of the tumor and the difficulty of locating it intraoperatively. The tumor nidus, the core responsible for the pain, was successfully identified and removed, relieving the boy of his symptoms instantly. The surgery was completed in just 30 minutes, and the boy experienced immediate relief. Post-surgery, he resumed normal activities the very next day. His long-term prognosis is excellent, allowing him to live a pain-free life without any limitations.”",
      "Dr. P. Sathyanarayanan, President of SRM Global Hospitals, commented, “This case demonstrates how modern imaging and surgical techniques can transform patient care. Precision in preoperative planning and surgical execution ensured a remarkable outcome, restoring the boy’s quality of life within a day. Our hospital is equipped with advanced infrastructure, a highly skilled multidisciplinary team, and a strong commitment to patient-centric care, making us a leader in delivering world-class medical outcomes.”",
      "Osteoid osteoma, though rare, ranks as the third most common benign bone tumor in children, with an occurrence rate of 1 in 1,00,000. It is more prevalent in boys and typically manifests in the second decade of life. This case highlights SRM Global Hospital’s commitment to leveraging advanced medical techniques to deliver exceptional patient outcomes.",
    ],
  },
  {
    id: 14,
    title: "SRM Global Hospitals hosts Happy Hearts to promote Healthy Heart",
    link: "https://srmglobalhospitals.com/event/srm-global-hospitals-hosts-happy-hearts-to-promote-healthy-heart/",
    image: "https://srmglobalhospitals.com/wp-content/uploads/2025/08/Happy-Hearts.png",
    localImage: "/images/press-releases/Happy-Hearts.png",
    excerpt: "Happy Hearts project at Mahindra World City, Chennai aims to promote healthy lifestyle with a series of activities hosted by SRM Global Hospitals. This campaign seeks to raise awareness and promote healthy lifestyle as an action to fight against cardiovascular diseases. Chennai, 6 October 2024: SRM Global Hospitals marks World Heart Day at Mahindra World ...",
    year: "2024",
    month: "December",
    date: "October 6, 2024",
    isoDate: "2025-08-29T05:53:00+00:00",
    category: "Community & Awareness",
    isDocumentScan: false,
    highlights: [
      "Happy Hearts project at Mahindra World City, Chennai aims to promote healthy lifestyle with a series of community wellness activities.",
      "This campaign seeks to raise awareness and promote active lifestyles as an action against cardiovascular diseases.",
    ],
    paragraphs: [
      "This campaign seeks to raise awareness and promote healthy lifestyle as an action to fight against cardiovascular diseases.",
      "Chennai, 6 October 2024: SRM Global Hospitals marks World Heart Day at Mahindra World City, Chennai by organising fun activities aimed at promoting fitness and total well-being. Over 500 individuals participated in the event and took the vow to make a step towards good health.",
      "Incorporating physical activity helps not only to maintain body weight but contributes to a healthy heart. The attendees were introduced to physical activities such as Zumba and Folk Dance which makes workouts fun, boosts one’s mood and overall wellbeing. Arts and crafts help in stimulating happy hormones, foster creativity and thinking also allowing to release stress. To de-stress from the daily mundane, a creative arts and crafts booth was also set up at the Mahindra World City catering to children and adults. A Dog Walk was also organised as a part of the activity lineups, making it a day of creativity and fun for all ages. The focus was on raising awareness about the importance of heart health.",
      "With fast paced and sedentary life, the campaign is a reminder for citizens to sign up for good health by working out regularly, taking professional help for managing stress, to pause and reflect on work-life balance, to consume nutritious meals and undergo periodical health checks",
    ],
  },
  {
    id: 15,
    title: "SRM Global Hospitals Achieves Milestone with Rare Hernia Surgery on 28-Day-Old Infant, Fourth Known Case in the World",
    link: "https://srmglobalhospitals.com/event/srm-global-hospitals-achieves-milestone-with-rare-hernia-surgery-on-28-day-old-infant-fourth-known-case-in-the-world/",
    image: "https://srmglobalhospitals.com/wp-content/uploads/2025/08/Hernia-Surgery.jpeg",
    localImage: "/images/press-releases/Hernia-Surgery.jpeg",
    excerpt: "While neonatal hernias are relatively common in preterm babies, Amyand\’s hernia is exceptionally rare. It affects only about 0.42% of these infants. The boy, born at just 28 weeks, underwent surgery on the 23rd day after his birth while under general anesthesia. Chennai, 12 September 2024: SRM Global Hospitals successfully performed a complex, three-part emergency ...",
    year: "2024",
    month: "December",
    date: "September 12, 2024",
    isoDate: "2025-08-29T05:52:16+00:00",
    category: "Surgical Excellence",
    isDocumentScan: false,
    highlights: [
      "While neonatal hernias are relatively common in preterm babies, Amyand’s hernia is exceptionally rare, affecting only about 0.42% of infants.",
      "The boy, born at just 28 weeks, underwent surgery on the 23rd day after birth while under general anesthesia.",
    ],
    paragraphs: [
      "The boy, born at just 28 weeks, underwent surgery on the 23rd day after his birth while under general anesthesia.",
      "Chennai, 12 September 2024: SRM Global Hospitals successfully performed a complex, three-part emergency surgery to save the life of a critically premature baby boy with Amyand’s hernia, a rare condition where the appendix is located in the groin—only the fourth case of its kind in medical history in the world.",
      "The boy, born at just 28 weeks, underwent surgery on the 23rd day after his birth while under general anesthesia. The procedure was successful, and post-operatively, the child recovered well, gaining weight to reach 2.06 kg and was discharged in good general condition.",
      "It was a highly challenging surgery as the boy, like any other premature baby, had an immature airway that made anesthesia more difficult and required precise management. Furthermore, the delicate tissues required careful surgical handling to avoid damage. Additionally, the low birth weight of the infant necessitated specialized postoperative care in the NICU to ensure proper recovery and support.",
      "The three parts of the surgery were: inguinal exploration, performed to examine and assess the groin area; appendectomy, to remove the appendix; and herniotomy, to repair the hernia by removing the hernia sac and fixing the defect in the abdominal wall. The entire procedure lasted for an hour. The pediatric surgery team, led by Dr. M. Saravana Balaji and Dr. N. Prathiba, carried out the procedure with the assistance of the anesthesia team, including Dr. K. Anand and Dr. Dheepak Kumaran, along with NICU doctors Dr. S. Subash and Dr. Ashok C.",
      "Commenting on the surgical feat, Dr. P. Sathyanarayanan, President, SRM Global Hospitals, said, “Successfully treating this critically premature baby with Amyand’s hernia—something seen only three times worldwide—highlights our team’s expertise. This complex surgery was a big challenge, but our skilled surgeons, anesthesia team, and NICU specialists handled it with incredible care. This case shows our hospital’s ability to tackle even the rarest conditions and set new standards in medical care.”",
      "In his comments, Dr. Saravana Balaji said, “The newborn had been in the Neonatal ICU since birth. The baby developed obstructed right inguinoscrotal swelling on the 23rd day. We had to do emergency surgery, as the condition was life-threatening. While neonatal hernias are relatively common in preterm babies, Amyand’s hernia is exceptionally rare. It affects only about 0.42% of these infants. Even rarer is the perforated appendix, occurring in just 0.1% of Amyand’s hernia cases. To date, only three such cases have been reported globally. Our prompt intervention was crucial in addressing this complex and rare condition.”",
      "The baby is doing well and steadily gaining weight under the care of his parents, Manju, a housewife, and Moorthy, a daily wage laborer—both from Chengalpattu",
    ],
  },
  {
    id: 16,
    title: "SRM Global Hospitals Honours Staff of Public Sector Insurance Companies with Free Consultations",
    link: "https://srmglobalhospitals.com/event/srm-global-hospitals-honours-staff-of-public-sector-insurance-companies-with-free-consultations/",
    image: "https://srmglobalhospitals.com/wp-content/uploads/2025/08/Free-Consultation.png",
    localImage: "/images/press-releases/Free-Consultation.png",
    excerpt: "Signs an MoU with General Insurance Agents\’ Federation Integrated (GIAFI), a premier association representing over 9,000 staff of all major public-sector health insurance companies in the country. Chennai, 28 August 2024: Acknowledging the significant role of insurance company officials in broadening health insurance coverage, SRM Global Hospitals, one of the city\’s largest multispeciality healthcare providers, ...",
    year: "2024",
    month: "December",
    date: "August 28, 2024",
    isoDate: "2025-08-29T05:50:38+00:00",
    category: "Strategic Partnership",
    isDocumentScan: false,
    highlights: [
      "Signs an MoU with General Insurance Agents’ Federation Integrated (GIAFI), representing over 9,000 staff of all major public-sector health insurance companies.",
      "Beneficiaries receive completely free initial consultations, along with privileged discounts on OPD consultations and diagnostics.",
    ],
    paragraphs: [
      "Chennai, 28 August 2024: Acknowledging the significant role of insurance company officials in broadening health insurance coverage, SRM Global Hospitals, one of the city’s largest multispeciality healthcare providers, has entered into a Memorandum of Understanding (MoU) with the General Insurance Agents’ Federation Integrated (GIAFI), a leading association representing employees of major public-sector health insurance companies, to offer free consultations and a range of other benefits to their 9,000-odd members across the country.",
      "According to the MoU, beneficiaries will receive a completely free initial consultation, along with discounts on OPD consultations and investigation fees, as well as cash benefits if out-of-pocket payments are necessary for treatments exceeding insurance coverage. The agreement is renewable every two years. These benefits can also be availed of by the family members of GIAFI members and their customers of mediclaim insurance products.",
      "Addressing the media, Dr. P. Sathyanarayanan, President, SRM Global Hospitals, said, “Signing this MoU with GIAFI marks a significant milestone for our hospital as we strive to bridge the gap in healthcare accessibility. With insurance coverage in India standing at only about 12%, we are acutely aware that this figure lags behind many other developing and developed countries. The role of insurance agents in expanding this coverage is crucial. We take great pride in recognising their contributions, and this partnership reinforces our commitment to improving healthcare outcomes for all.”",
      "In his comments, Dr. V. P. Chandrasekaran, Chief Operating Officer, SRM Global Hospitals, said, “We are proud to extend our special privileges to GIAFI members across India in recognition of their incredible social impact. We are committed to offering exclusive medical services and VIP privileges not only to GIAFI members but also to their families and policyholder customers. We will be introducing special health checkups and preventive care packages at affordable rates for GIAFI members, ensuring that they receive the best possible care.”",
      "In his comments, Mr. Prashant R. Mhatre, All India President, GIAFI, said, “We would like to express our heartfelt gratitude to SRM Global Hospitals for their generous support. We approached the hospital to provide medical services for our members, family members, and customers who purchase health insurance policies from us. We are delighted that SRM Global Hospitals has graciously accepted our request and has gone above and beyond by offering VIP Privilege membership benefits. This partnership ensures ease of access to cashless facilities and advanced healthcare services for all beneficiaries, meeting their medical needs with the highest level of care.”",
    ],
  },
  {
    id: 17,
    title: "SRM Global Hospitals Inks Pact with Global Doctors to Treat Patients from Malaysia, Asia Pacific",
    link: "https://srmglobalhospitals.com/event/srm-global-hospitals-inks-pact-with-global-doctors-to-treat-patients-from-malaysia-asia-pacific/",
    image: "https://srmglobalhospitals.com/wp-content/uploads/2025/08/Inkspact-Image.png",
    localImage: "/images/press-releases/Inkspact-Image.png",
    excerpt: "Global Doctors Alliance boasts of a growing network of internationally renowned medical practice groups in Malaysia, Indonesia, Thailand, Japan, Turkey and China. The partnership seeks to enhance the range of services available to the international patients, particularly those with overseas citizenship of India, quality healthcare at world class infrastructure \– immediately and at a highly ...",
    year: "2024",
    month: "December",
    date: "August 2024",
    isoDate: "2025-08-29T05:48:41+00:00",
    category: "Strategic Partnership",
    isDocumentScan: false,
    highlights: [
      "Global Doctors Alliance boasts of a growing network of internationally renowned medical practice groups in Malaysia, Indonesia, Thailand, Japan, Turkey and China.",
      "The partnership seeks to enhance services available to international patients with world-class infrastructure immediately and affordably.",
    ],
    paragraphs: [
      "The partnership seeks to enhance the range of services available to the international patients, particularly those with overseas citizenship of India, quality healthcare at world class infrastructure – immediately and at a highly affordable cost.",
      "Chennai, 30 July 2024: SRM Global Hospitals will provide treatment for patients from Malaysia and other Asia Pacific countries in various specialties in Chennai, following an MoU the hospital signed today with Global Doctors – Malaysia, part of the Global Doctors Alliance, which represents a growing network of affiliated medical centers in Malaysia, Indonesia, Thailand, Japan, Turkey and China.",
      "As per the agreement, SRM Global Hospitals will also provide teleconsultations to patients of Global Doctors and share clinical knowledge with their healthcare professionals. The hospital is expected to get patients and medical tourists of Global Doctors mainly for treatments in specialties like cardiology, cardiothoracic, neurology, gastroenterology, and orthopedics.",
      "The MoU signing ceremony was held in the presence of Dato’ Dr Sharifah Fauziah Alhabshi, Executive Chairman, Dr Navindra Nageswaran, Medical & Managing Director, Ms. Suhaila Mohd Kassim, COO & DON, Ms. Nagiah Alidrus, Top Glove Global Doctors Medical Centre, Malaysia, Manager, and Mr. Mohamed Sahriff – Director of Medical & Business Development, Global Doctors.",
      "In his comments about the partnership, Dr. P. Sathyanarayanan, President, SRM Group of Companies, said, “We are happy to partner with Global Doctors, and become a partner hospital of its alliance that comprises internationally renowned medical practice groups from Malaysia, Indonesia, Thailand, Japan, Turkey and China. We can provide a full range of pediatric and adult care services ranging from primary to secondary care to tertiary in all specialties. What makes a big difference for international patients is that hospitals in India, like SRM Global Hospitals, can offer quality healthcare at world class infrastructure – immediately and at a highly affordable cost. We thank Global Doctors for including our hospital in the network and let us provide seamless and quality medical care to patients from across borders.”",
      "Global Doctors is in the frontline for providing primary care, secondary care and pre-hospital care with a strong network of tertiary care hospitals in the Asia Pacific region. It currently has 15 affiliate medical centers across China, Thailand, Japan, Turkey, Indonesia and Malaysia. The Global Doctors Alliance is aimed at facilitating ease of referrals between countries and to ensure that their patients receive the same high quality of healthcare and service standards in any of the countries of the partner medical centers.",
    ],
  },
  {
    id: 18,
    title: "SRM Global Hospitals Cures Jaundice of End-Stage Cancer Patient with Advanced Endoscopic-Ultrasound Technology",
    link: "https://srmglobalhospitals.com/event/srm-global-hospitals-cures-jaundice-of-end-stage-cancer-patient-with-advanced-endoscopic-ultrasound-technology/",
    image: "https://srmglobalhospitals.com/wp-content/uploads/2025/08/Jaundice-Case-Image.png",
    localImage: "/images/press-releases/Jaundice-Case-Image.png",
    excerpt: "The 78-year-old pancreatic cancer patient from Bangladesh is relieved of all his jaundice-linked complaints such as loss of appetite, severe itching and sleeplessness. His jaundice is the result of a tumour obstructing the bile duct. The minimally invasive procedure based on an advanced endoscopic-ultrasound technology created new internal pathway for the bile to drain. Chennai, ...",
    year: "2024",
    month: "December",
    date: "August 2024",
    isoDate: "2025-08-29T05:48:11+00:00",
    category: "Surgical Excellence",
    isDocumentScan: false,
    highlights: [
      "The 78-year-old pancreatic cancer patient from Bangladesh is relieved of all his jaundice-linked complaints such as loss of appetite and severe itching.",
      "The minimally invasive procedure based on advanced endoscopic-ultrasound technology created a new internal pathway for the bile to drain.",
    ],
    paragraphs: [
      "His jaundice is the result of a tumour obstructing the bile duct. The minimally invasive procedure based on an advanced endoscopic-ultrasound technology created new internal pathway for the bile to drain.",
      "Chennai, 1 July 2024: SRM Global Hospitals, a leading multispecialty hospital in the city, successfully treated jaundice of a 78-year-old end-stage pancreatic cancer patient from Bangladesh using a minimally invasive procedure known as choledochoduodenostomy, guided by an advanced endoscopic ultrasound technology. The cause of his jaundice was the obstruction of his bile duct by a tumour, leading to the accumulation of the bile. The procedure created a stent-supported new pathway between the bile duct and the duodenum (a part of the small intestine), paving the way for the bile to drain.",
      "The main medical outcome of the procedure is the enhanced quality of life of the patient, who was suffering from loss of appetite, severe itching and sleeplessness. Besides, his palliative chemotherapy had to be stopped. However, following the procedure, the patient is able to have food to his heart’s content; and has found relief from severe itching and sleeplessness. The patient has gone back to his own country where he will undergo palliative cancer care.",
      "According to Dr. N.A. Rajesh, Gastroenterologist, SRM Global Hospitals, who performed the procedure, the end-stage cancer patient developed jaundice, as a result of the tumour obstructing his bile duct. The patient lost his appetite and was unable to have food. He had complaints of severe itching and sleeplessness. Further, he could not continue with the chemotherapy treatment with jaundice. Considering the patient’s old age, and physical weakness, we opted for a minimally-invasive endoscopic procedure with the support of an advanced endoscopic ultrasound technology and created a surgical connection between the common bile duct and an alternative portion of the duodenum, a part of the small intestine, for the bile to drain. We have also used a newly developed stent (‘electro-cautery lumen apposing metal stent’) to strengthen the new pathway.",
      "Dr Rajesh explained that the traditional treatment for this type of bile duct obstruction (medically, ‘malignant biliary obstruction’) is to place a self-expanding metallic stent through the naturally occurring opening of the bile duct in the duodenum. This is done by a procedure called Endoscopic Retrograde Cholangiopancreatography (ERCP). When ERCP is not possible, Percutaneous Transhepatic Biliary Drainage (PTBD) is done in which an external bag is temporarily fixed for the bile to drain and once the patient’s general condition improves, palliative biliary bypass surgery is done to re-route the flow of bile into the small intestine. However, senior citizens with end-stage pancreatic cancer can hardly endure these demanding procedures. Besides, there is a risk of infection with PTBD, and the external bag can cause inconvenience for the patient. However, with the endoscopic ultrasound-guided choledochoduodenostomy, major surgical interventions and associated risks were avoided.",
      "In his comments, Dr. P. Sathyanarayanan, President, SRM Group of Companies, said that the quality of life should be accorded a high priority even for the patients whose conditions cannot be cured. After this 30-minute procedure, the health condition of the patient improved dramatically with drastic reduction in jaundice and quick improvement in appetite. The itching stopped completely. The patient is back to his country where he will undergo palliative chemotherapy.",
      "The endoscopic ultrasound-guided choledochoduodenostomy is a recent modality. The main advantage is that it generates virtual images of internal organs using high-frequency sound waves, instead of video cameras. SRM Global Hospitals is one of the few centres in the country to perform the procedure which has high clinical success rates and low adverse events.",
    ],
  },
  {
    id: 19,
    title: "Early Detection Key to Treating Thyroid Cancer",
    link: "https://srmglobalhospitals.com/event/early-detection-key-to-treating-thyroid-cancer/",
    image: "https://srmglobalhospitals.com/wp-content/uploads/2022/12/close-up-hands-holding-purple-ribbon-with-stethoscope_23-2148283514.webp",
    localImage: "/images/press-releases/close-up-hands-holding-purple-ribbon-with-stethoscope_23-2148283514.webp",
    excerpt: "Observed annually on 25 May, aims to raise awareness on thyroid disorders, early detection, and management. Chennai, May 24, 2024: Thyroid cancer is the most common cancer of the endocrine system and occurs in all age groups. In India, the number of new cases of thyroid cancer is 13.9 per 100,000 men and women per ...",
    year: "2024",
    month: "December",
    date: "May 24, 2024",
    isoDate: "2025-08-26T13:41:42+00:00",
    category: "Community & Awareness",
    isDocumentScan: false,
    highlights: [
      "Observed annually on 25 May, World Thyroid Day aims to raise awareness on thyroid disorders, early detection, and management.",
      "Thyroid cancer is the most common cancer of the endocrine system, with exceptionally high cure rates when detected early.",
    ],
    paragraphs: [
      "Chennai, May 24, 2024: Thyroid cancer is the most common cancer of the endocrine system and occurs in all age groups. In India, the number of new cases of thyroid cancer is 13.9 per 100,000 men and women per year. Among both men and women, the number of new cases of thyroid cancer are increasing at a faster rate than any other type of cancer. The Madras Metropolitan Tumor Registry (MMTR) Chennai has also recorded an increasing incidence in thyroid cancers over the last 25 years, the increase can be partly attributed to increasing use of neck imaging (Ultrasound / CT scans / PET-CT scans) resulting in early detection and thereby treatment of smaller thyroid cancers.",
      "Thyroid cancers are a diverse group of malignancies ranging from indolent micropapillary carcinomas which has little effect on life expectancy to highly lethal anaplastic carcinomas which are invariably fatal. Papillary and follicular cancers, often referred to as “well-differentiated thyroid cancers (WDTC), are the most common types of thyroid cancer. Together, they account for about 90% of thyroid cancers.",
      "According to Dr. R. Nanda Kumar, General Medicine, Senior Consultant, SRM Global Hospitals, said, “I see almost 400 plus patients a year who suffer from this disease. Out of these 80 per cent of the patients fall in the low-risk category. That means with the right treatment and regular follow ups, these patients can live a decent quality of life.”",
      "The typical presentation of a thyroid cancer is in the form of a painless thyroid nodule. The other symptoms of thyroid cancers, which are invariably suggestive of advanced disease, include pain in the lower front part of the neck, swollen lymph nodes in the neck, hoarseness of voice, loss of weight and appetite, and/or trouble in breathing and swallowing. Physical examination, blood tests, thyroid ultrasound and fine-needle aspiration biopsies are usually done to detect thyroid cancer in a patient.",
      "The primary management for most patients with thyroid cancer is surgical removal of the entire thyroid gland (Total thyroidectomy). Following surgery, the patients are required to undergo radioactive iodine scans and radioactive ablative procedures when indicated. To have a successful outcome of this procedure all patients are required to have high levels of thyroid-stimulating hormone (TSH or thyrotropin) in the blood which can be given through either by withdrawing thyroid hormone therapy or recombinant thyroid stimulating hormone injections. Withdrawal of thyroid hormones can lead to moderate to severe hypothyroidism which may impact the quality of life while the injections to raise TSH levels may be costly but helps patients to remain on a normal lifestyle. Subsequently, the patients take thyroid replacement hormone medicine throughout their lives.",
      "For the procedure to be successful, your doctor may advise initial thyroid treatment with the thyroid medication for hyperthyroidism or hypothyroidism to make sure that the TSH are maintained. After the surgery, the patient may need to take thyroid tablets to maintain the TSH levels.",
      "“As with all cancers, timely detection and appropriate treatment are the prerequisites for a better outcome,” says Dr. Nanda Kumar, adding, “a successful treatment plan involves adopting a collaborative approach and combining the expertise of head and neck surgeons, endocrinologists, and a nuclear physician. Most of the thyroid cancers are treatable with surgery and other associated treatment options. Total thyroidectomy is a safe procedure in skilled hands; the morbidity created by a poorly performed thyroid gland operation can exceed the morbidity caused by leaving some thyroid lesions alone. Patients with well differentiated thyroid cancers in general have a favorable prognosis compared with that of patients with many other solid tumors.”",
      "“On World Thyroid Day, I would like to request everyone that if you feel a lump in your throat or swelling, do visit a doctor. Most people would rather wait than act, in this case specifically the sooner you act the sooner you get treated. There is also a need amongst doctors to counsel the patients after surgery and tell them the importance of regular follow ups,” said Dr. Nanda Kumar.",
      "About Thyroid Cancer Thyroid cancer is a malignant growth or tumor in the thyroid gland. It is the most common cancer of the endocrine system (the endocrine system consists of glands throughout the body that produce hormones). Thyroid cancer occurs in men as well as in women and can occur at any age. However, thyroid cancer occurs almost three times more often in women than in men. Among both men and women, the number of new cases of thyroid cancer is increasing at a faster rate than any other type of cancer. There is a very high treatment success rate for most types of thyroid cancer when diagnosed and treated early. Despite high treatment success, it is important to know that up to one-third of thyroid cancers can recur, sometimes even decades after the initial treatment. For this reason, thyroid cancer requires long-term monitoring to make sure that the cancer has not come back, or if it has, to begin treatment right away.",
      "The primary management for most patients with thyroid cancer is surgical removal of the entire thyroid gland (Total thyroidectomy). Following surgery, the patients are required to undergo radioactive iodine scans and radioactive ablative procedures when indicated. To have a successful outcome of this procedure all patients are required to have high levels of thyroid-stimulating hormone (TSH or thyrotropin) in the blood which can be given through either by withdrawing thyroid hormone therapy or recombinant thyroid stimulating hormone injections. Withdrawal of thyroid hormones can lead to moderate to severe hypothyroidism which may impact the quality of life while the injections to raise TSH levels may be costly but helps patients to remain on normal lifestyle. Subsequently, the patients take thyroid replacement hormone medicine throughout their lives. For the procedure to be successful, your doctor may advise initial thyroid treatment with the thyroid medication for hyperthyroidism or hypothyroidism to make sure that the TSH are maintained. After the surgery, the patient may need to take thyroid tablets to maintain the TSH levels.",
    ],
  },
  {
    id: 20,
    title: "SRM Global Hospitals Implants a First-of-Its-Kind Heart Valve in 77-Year-Old Patient",
    link: "https://srmglobalhospitals.com/event/srm-global-hospitals-implants-a-first-of-its-kind-heart-valve-in-77-year-old-patient/",
    image: "https://srmglobalhospitals.com/wp-content/uploads/2025/08/77-Years-Heart-Valve-Team-Image.png",
    localImage: "/images/press-releases/77-Years-Heart-Valve-Team-Image.png",
    excerpt: "The implanted valve, named Edwards SAPIEN 3 Ultra, ranks among the most advanced and the safest heart valves globally. Chennai, May 14, 2024: The medical team at SRM Global Hospitals has successfully performed a catheter-based surgery and implanted an artificial aortic valve in a 77 year-old patient, who developed severe calcified iodic stenosis, a condition ...",
    year: "2024",
    month: "December",
    date: "May 14, 2024",
    isoDate: "2025-08-26T09:49:40+00:00",
    category: "Surgical Excellence",
    isDocumentScan: false,
    highlights: [
      "The implanted valve, named Edwards SAPIEN 3 Ultra, ranks among the most advanced and safest artificial heart valves globally.",
      "Catheter-based surgery avoided open-heart intervention in a 77-year-old patient with severe calcified aortic stenosis.",
    ],
    paragraphs: [
      "Chennai, May 14, 2024: The medical team at SRM Global Hospitals has successfully performed a catheter-based surgery and implanted an artificial aortic valve in a 77 year-old patient, who developed severe calcified iodic stenosis, a condition characterised by the narrowing of the heart valve. The implanted valve, named Edwards SAPIEN 3 Ultra, ranks among the most advanced and safe heart valves globally. This patient is the inaugural recipient of this cutting-edge technology.",
      "In another first, the surgery used an innovative sheath (Edwards E-Sheath) that ensured the safe delivery of the valve, preventing any damage to surrounding tissues, as it was guided through a blood vessels from the groin to the heart. Following the minimally-invasive surgery conducted on May 9, the patient recovered swiftly. He started walking and resumed a normal diet the very next day of the 55-minute procedure that went eventless.",
      "In his comments, Dr. P. Sathyanarayanan, President, SRM Global Hospitals, said, “In the modern age, where diseases like heart conditions weigh heavily on communities, it’s crucial for hospitals to embrace cutting-edge medical advancements. This enables them to offer patients the assurance of safety and an improved quality of life. At SRM Global Hospitals, we continuously seek out and implement the latest proven solutions. Keeping this ethos in mind, we’ve employed Edwards SAPIEN 3 Ultra valve and Edwards E-Sheath technology to ensure optimal and safe treatment for a senior patient who has previously undergone surgical intervention. We are happy that the patient, the first one in India to be implanted with this latest innovation, is back to leading a normal life.”",
      "In his comments, Dr. T.R. Muralidharan, Director of Institute of Cardiac Sciences, SRM Global Hospitals, who performed the surgery, said that the patient had been on medication for stenosis. But as the condition became severe, he required surgical intervention. However, the patient had underwent a bypass surgery about 12 years ago. Considering this past surgical intervention and his old age, an open heart surgery was ruled out. Hence we chose Transcatheter Aortic Valve Implantation surgery. Fortunately, Edwards SAPIEN 3 Ultra was just launched in India. Since the device promised significant reduction in major vascular complications such as valve leak, we opted for it. The patient became the first one in India to have been implanted with this most advanced artificial aortic valve.",
      "Valve leak – or paravalvular leak, is a serious complication. It is associated with valve replacement or implantation surgery. It occurs when a space is left between natural heart tissue and the replaced valve. Several studies have proved that Edwards SAPIEN 3 Ultra minimises this risk with its innovative design. It reduces the risk of heart block leading to permanent pacemaker.",
    ],
  },
  {
    id: 21,
    title: "SRM Global Hospitals Introduces X-Ray Free, 3D Model-Based Imaging for Treating Irregular Heartbeats",
    link: "https://srmglobalhospitals.com/event/srm-global-hospitals-introduces-x-ray-free-3d-model-based-imaging-for-treating-irregular-heartbeats/",
    image: "https://srmglobalhospitals.com/wp-content/uploads/2025/08/3D-Model-Team-Image.png",
    localImage: "/images/press-releases/3D-Model-Team-Image.png",
    excerpt: "EnSite is an advanced non-fluoroscopic mapping system that avoids or minimizes radiation exposure but provides highly detailed, 3D models and maps to help doctors more effectively diagnose the sources of irregular heart rhythms. Chennai, 30 April 2024: SRM Global Hospitals has become one of the few hospitals in the country to use an x-ray free, ...",
    year: "2024",
    month: "December",
    date: "April 30, 2024",
    isoDate: "2025-08-26T09:48:52+00:00",
    category: "Clinical Milestone",
    isDocumentScan: false,
    highlights: [
      "EnSite is an advanced non-fluoroscopic mapping system that avoids or minimizes radiation exposure while providing highly detailed 3D models.",
      "SRM Global Hospitals becomes one of the few hospitals in the country to use x-ray free 3D imaging for treating irregular heartbeats.",
    ],
    paragraphs: [
      "Chennai, 30 April 2024: SRM Global Hospitals has become one of the few hospitals in the country to use an x-ray free, 3D model-based imaging system to identify the abnormal heart tissues that cause irregular heart rhythms (cardiac arrhythmias) before treating them using a catheter-based procedure known as ablation. The hospital adopted a cutting-edge technology, EnSite Cardiac Mapping System, in treating a 57-year-old male, recently, who suffered from supraventricular tachycardia, a condition of faster than a normal heartbeat. Dr. T. R. Muralidharan, Director of Institute of Cardiac Sciences, SRM Global Hospitals, and his team used the imaging system and did ablation, which is a minimally invasive procedure. The patient is completely cured of his arrhythmia.",
      "Conventionally, X-ray fluoroscopy, a type of imaging procedure that uses several pulses of an X-ray beam to take real-time footage of tissues inside the body, is used as the primary cardiac imaging modality in diagnosing tissues causing cardiac arrhythmias. However, the use of x-ray means radiation exposure that can pose serious health risks especially for children, pregnant women, senior citizens, and the medical team. EnSite is based on an advanced non-fluoroscopic mapping technology that avoids or minimizes radiation exposure, yet provides highly detailed, three-dimensional models and maps that help doctors more effectively diagnose the sources of irregular heart rhythms.",
      "In his comments, Dr. Muralidharan said, “Our heartbeat is governed by a series of electrical impulses. But when the normal flow of electrical signals is disrupted, it results in palpitations. The condition feels like the heart has skipped a beat or added an extra beat. Palpitations are typically harmless and resolve on their own without any treatment. But they may also indicate a more serious underlying condition, such as: arrhythmia, abnormal heart valves, heart disease, and congestive heart failure. Conventionally, X-ray imaging is used to figure out the abnormal tissues that disrupt the flow of electrical signals. However, x-ray imaging causes radiation exposure. Hence it is not safe. In contrast, the EnSite mapping system can create the required geometric contours of those relevant cardiac structures and chambers. It is used as an alternative to x-ray fluoroscopy.”",
      "Speaking about this milestone, Dr. P. Sathyanarayanan, President, SRM Group of Companies stated, “We constantly work on delivering top quality healthcare services that result in fast healing and ensuring safety and comfort of our patients. Our skilled experts and the new technology, EnSite X used in correcting irregular heart rhythms promise a transformative shift in diagnosis and assessment of heart health.”",
      "Though non-fluoroscopic cardiac mapping systems are becoming standard of care in the treatment of palpitations, it requires experienced electrophysiology physicians. The competent team of SRM Global Hospitals offers this treatment for patients suffering from all types of arrhythmia.",
    ],
  },
];
